### ISSUE TITLE
Database backup contains complete backup

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#1006]
This happens on a local install I have which has a `wordpress` subfolder. Not sure if that is the reason, but the database backup is quite big and when I download the zip, it contains a full backup.

<img width="531" alt="screenshot 2016-02-29 12 02 05" src="https://cloud.githubusercontent.com/assets/30460/13393926/6e379770-dedc-11e5-807a-7e31c0561e09.png">

**Comment by willmot** [comment]
That's pretty odd. If it was simply including a previous complete backup then I'd expect it to be the Zip itself not the contents.

Does this happen even when you have no previous complete backups?

**Comment by pdewouters** [comment]
yeah, probably a weird side effect of my testing. I deleted all backups and started again and now it doesn't happen.

**Comment by pdewouters** [comment]
<img width="453" alt="screenshot 2016-02-29 12 16 45" src="https://cloud.githubusercontent.com/assets/30460/13394421/26167cdc-dee0-11e5-9147-82e9950a9dbd.png">

I do get a strange calculated size for the database though, see 12MB vs 191Kb

**Comment by willmot** [comment]
@pdewouters that's expected as db's generally compress 10-20x.

**Comment by pdewouters** [comment]
ah, right. I always think it;s the compressed size
