### ISSUE TITLE
Using excludes together with wp-cli does not work

### ISSUE THREAD

**Issue by duritong** [humanmade/backupwordpress#1009]
Trying to use excludes with the wp cli fails:

    $ wp --path=www --no-color backupwordpress backup --destination=private/wp_update_backup --excludes='wp-content/backupwordpress-*'
    PHP Catchable fatal error:  Argument 1 passed to HM\BackUpWordPress\Backup::set_excludes() must be an instance of HM\BackUpWordPress\Excludes, string given, called in /var/www/vhosts/xxx/www/wp-content/plugins/backupwordpress/classes/class-backupwordpress-wp-cli-command.php on line 90 and defined in /var/www/vhosts/xxx/www/wp-content/plugins/backupwordpress/classes/backup/class-backup.php on line 34
    Catchable fatal error: Argument 1 passed to HM\BackUpWordPress\Backup::set_excludes() must be an instance of HM\BackUpWordPress\Excludes, string given, called in /var/www/vhosts/xxx/www/wp-content/plugins/backupwordpress/classes/class-backupwordpress-wp-cli-command.php on line 90 and defined in /var/www/vhosts/xxx/www/wp-content/plugins/backupwordpress/classes/backup/class-backup.php on line 34

Removing the excludes works fine

    $ wp --path=www --no-color backupwordpress backup --destination=private/wp_update_backup 
    Success: Backup fertiggestellt:/var/www/vhosts/xxxx/private/wp_update_backup/backup.zip

Everything is up2date

    $ wp --path=www cli version
    WP-CLI 0.22.0
    $ wp --path=www --no-color plugin list | grep backup
    | backupwordpress          | active   | none   | 3.4.5   |

**Comment by willmot** [comment]
Thanks for the bug report, we'll get this fixed 👍
