### ISSUE TITLE
[Insight] PHP code should not contain unreachable code - in admin/schedule-settings.php, line 95

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#1016]
**[in admin/schedule-settings.php, line 95](https://github.com/humanmade/backupwordpress/blob/c78d32b7d13f5e3ecfdb66df948f847ccbe35e6a/admin/schedule-settings.php#L95)**

> This code is unreachable.

```php
				<?php submit_button( __( 'Done', 'backupwordpress' ) ); ?></form><?php break; ?><?php } ?><?php endforeach; ?></div>
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/8f0e4684-e304-4aac-9fe9-142989664dd9/analyses/740)_

**Comment by willmot** [comment]
@pdewouters did you intend to create this issue? Doesn't seem to be correct as that code is reachable.

**Comment by pdewouters** [comment]
False positive then.
