### ISSUE TITLE
Plugin automatically starts running after plugin update

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1019]
Have heard this from a couple people - listing here as a potential bug for you guys to weigh in on. 

For these users, BackUpWordpress suddenly started running when they update plugins & when login. 

Users are asking: Is this a new feature? Should it be happening?

**Comment by willmot** [comment]
It shouldn't be happening but it's something I've noticed does happen. We have a ticket for the issue here: https://github.com/humanmade/backupwordpress/issues/758
