### ISSUE TITLE
No intercom data for certain sites

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#1023]
Why do some sites not provide any intercom data?

<img width="324" alt="screenshot 2016-03-07 11 14 05" src="https://cloud.githubusercontent.com/assets/30460/13567863/c12a7fa0-e455-11e5-8585-bd575863fd9b.png">

**Comment by willmot** [comment]
Is it people who just email `backupwordpress@hmn.md` directly?

**Comment by pdewouters** [comment]
ah might be. maybe @katmoody  knows

**Comment by katmoody** [comment]
I've been trying to keep track of that too - I think it's only attached when the email is already linked to an account or when the support module doesn't actually load and instead opens an email (happens on some sites).

**Comment by willmot** [comment]
@pdewouters I think this can be closed?
