### ISSUE TITLE
Allow access to existing backups even if new backup aren't possible

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#1030]
Currently if any of the checks in `is_backup_possible` fail we show a warning message and completely disable access to all plugin functionality.

For example if disk space is low you'll see the following:

<img width="1085" alt="screen shot 2016-03-12 at 17 46 27" src="https://cloud.githubusercontent.com/assets/308507/13724362/d0213d5e-e87a-11e5-99b4-b4ef3da9868d.png">

This is more overbearing than we need to be. Instead we should allow access to all functionality except running new backups.
- [ ] Disable running manual backups

**Comment by willmot** [comment]
We should additionally only block access to database and complete backups whilst allowing files only backups if PDO + mysqldump is missing but ZipArchive is available.

**Comment by katmoody** [comment]
Alternatively, if there isn't enough space to do a full site backup, there should also still be the option to back up the database. Reported here: https://wordpress.org/support/topic/your-server-only-has-x-gb-of-disk-space-left-problem?replies=1

**Comment by SEWilco** [comment]
I think this is a bug, not an enhancement issue. Taking away all functionality means users can't adjust settings and delete files so as to fix the problem. (But then, I don't understand why 33% of disk space in my system isn't enough, when that's enough for well over a dozen more backups.)

**Comment by pdewouters** [comment]
also there's a typo : `You're server`

**Comment by willmot** [comment]
> (But then, I don't understand why 33% of disk space in my system isn't enough, when that's enough for well over a dozen more backups.)

@SEWilco that definitely shouldn't be happening. Could you drop a screenshot of the error you're getting?

**Comment by SEWilco** [comment]
@willmot:
Your server only has 9 GB of disk space left which probably isn't enough to complete a backup. Try deleting some existing backups or other files to free up space.

**Comment by willmot** [comment]
@SEWilco and how big is your backup (with and without excludes)?

**Comment by SEWilco** [comment]
@willmot Less than 400MB with excludes. I think. I don't know because I can't make the plugin tell me what my excludes are.

**Comment by SEWilco** [comment]
@willmot Well, that's interesting. I managed to delete enough to make only 47% of disk be in use (15GB available), and now the plugin says: "Backup my database and files (**104 MB**) weekly..." but the backup is **451MB**. The two excluded directories are not in the backup file. DB backup is 30MB (5MB compressed).

**Comment by SEWilco** [comment]
I still think this should be treated as a bug and not an enhancement issue. It's not working on my other servers, one of which has 13GB and that's not enough for the plugin. No further details will be available from me, as I'm removing the plugin.

**Comment by katmoody** [comment]
Related to #1063 and possibly #1062

**Comment by libby-barker** [comment]
- [ ] Remove check from around admin

- [ ] Apply check to button to do a manual button

**Comment by sambulance** [comment]
PR: https://github.com/humanmade/backupwordpress/pull/1133

**Comment by katmoody** [comment]
So is this one complete now? @sambulance

**Comment by mikeselander** [comment]
Looks like this was merged in before 3.6.3? Can this be closed?

**Comment by katmoody** [comment]
Hey @mikeselander - when I look at #833 I don't see that it's been merged yet? It looks like Sam was waiting on a code review from Shady, maybe?

**Comment by sambulance** [comment]
#833 needs an additional review because of the changes made here. This is done and merged now.
