### ISSUE TITLE
Unable to edit date and time settings

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1037]
On this site, the inability to edit date and time settings is coinciding with the backup not working as well. 

On Intercom: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/2001256445

From the ticket: 

>The backup date time is set but then reads "Thursday in 1970" as the backup cron 😀 ....and if I click "Run now" it wheels for a sec and then just goes back to a checkmark and nothing - no error. Database only also has the weird date listed - but it does run successfully

>...when I mouse over the day ...the popup info box thing says "The next backup will be on January 1, 1970 at 12:00 am UTC

**Comment by willmot** [comment]
I haven't been able to reproduce this. @katmoody are we able to get FTP access to the server this was happening on?

 Let's re-open if/when the issue returns and we have access to a server where we can reproduce and debug.
