### ISSUE TITLE
Stop using `mysql` to check cli database access

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#1040]
We're running into issues where the `mysql` isn't available but `mysqldump` is, in those instances we cause users to fallback to `PDO` when in reality it would be fine to use `mysqldump`.

Let's just remove that check and let mysqldump run, it will fallback anyway.

**Comment by katmoody** [comment]
Is this error an indication of this issue @willmot? 

```Mysqldump: mysqldump: Got error: 145: Table './ArabiaHolidaysCom/wp_wfLeechers' is marked as crashed and should be repaired when using LOCK TABLES

IMysqldump: SQLSTATE[HY000]: General error: 145 Table './ArabiaHolidaysCom/wp_wfLeechers' is marked as crashed and should be repaired```

If not, I'll open a new ticket - but the backup works despite this error, making me think that the error is coming up on the MySQLDump but the fallback is still working. (also - should I tell Wordfence about that table crashing - "wp_wfLeechers" is one of theirs I think - it's the third time that error has come up on one of the sites contacting us?)

**Comment by willmot** [comment]
@katmoody nope different issue, they have crashed tables and need to repair them. See https://github.com/humanmade/backupwordpress/issues/836
