### ISSUE TITLE
Remove use of `DirectoryIterator::getExtension()`

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#1041]
It wasn't available until PHP 5.3.6 and we have 5.3.2 as a minimum.

**Comment by pdewouters** [comment]
Replace with `pathinfo($entity->getFilename(), PATHINFO_EXTENSION);`

**Comment by katmoody** [comment]
Associated ticket in Intercom: 
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/4394095006

Just let me know when we have a potential fix since he's waiting on that to test ;-)

**Comment by willmot** [comment]
Fixed in 3.6
