### ISSUE TITLE
Warning with Process

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#1043]
`Warning: proc_open(): CreateProcess failed, error code - 5 in D:\Inetpub\wwwroot\PoliceWP\wp-content\plugins\backupwordpress\vendor\symfony\process\Process.php on line 290`

**Comment by katmoody** [comment]
Here's a report from wp.org with this error: 
https://wordpress.org/support/topic/error-code-5-in-processphp-on-line-290?replies=2

and also on Intercom: 
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/4391212782
with the screenshot (harder to see) 
[php%20error.pdf](https://github.com/humanmade/backupwordpress/files/188109/php.20error.pdf)

**Comment by pdewouters** [comment]
We might need to use `exec` on Windows ... joy

https://github.com/mikehaertl/phpwkhtmltopdf/issues/56

**Comment by willmot** [comment]
`Process` purports to work on Windows and if we do hit the error we'll just fallback to PHP.

https://github.com/humanmade/backupwordpress/commit/b2532e1fb464a42a313262396b399c1ef6232577 should mean we won't show this warning if the PHP fallback was successful.

**Comment by katmoody** [comment]
Related to newer error that is (as of yet) unsolved: #1057 -should this be reopened or start with newer issue?
