### ISSUE TITLE
Process error with Zip

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1046]
`Zip: The process has been signaled with signal "15"`
The backup size won't complete (just spins) and the backups don't work. 

Intercom ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/2001101400

**Comment by willmot** [comment]
That means something is killing the backup process, will be helped by 3.6 and https://github.com/humanmade/backupwordpress/pull/1025

**Comment by willmot** [comment]
Closing as a dupe of https://github.com/humanmade/backupwordpress/pull/1025
