### ISSUE TITLE
Error without Activation due to Erroneous Version Reported

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1047]
In the forums, there are a few people reporting that they are receiving the following error: 
`BackUpWordPress requires PHP version 5.3.2 or later and WordPress version 3.9 or later to run. It has not been activated.`
This, despite the WordPress being at version 3.4.2 and PHP being 5.4+

Wp.org post: https://wordpress.org/support/topic/can-not-activate-v-345?replies=3

**Comment by pdewouters** [comment]
@katmoody can you ask them what it says in the server tab of the help screen?

**Comment by katmoody** [comment]
They aren't able to activate the plugin at all so they wouldn't have a server tab of the help screen :(

**Comment by willmot** [comment]
@katmoody I'm almost certain that they aren't on PHP 5.4+.

Best bet would be to get them to install https://wordpress.org/plugins/wordpress-php-info/ and then see what version that reports. I'm almost certain that they are wrong and they just think they are on a higher version of PHP but actually aren't.

@katmoody probably worth having a support page about this which links to that plugin.

**Comment by pdewouters** [comment]
> They aren't able to activate the plugin 
Doh! sorry for stupid answer...as Tom says, it often happens that wherever they get the info about the version number is not actually correct. I think @owaincuvelier might have created a page on the support centre for this.

**Comment by owaincuvelier** [comment]
@katmoody this isn't that uncommon. Basically, if BackUpWordPress says they're not on a certain version of PHP, then they probably aren't. Hosts are TERRIBLE at misreporting PHP version numbers. I would typically get them to verify, sometime I'd just tell them to contact their host directly.

**Comment by katmoody** [comment]
Good notes from all - that was my initial thinking. I'll wait to close until this is verified.

**Comment by katmoody** [comment]
Also updated the PHP Version Error page already on site for now to include that plugin ;-) 

https://bwp.hmn.md/support-center/unsupported-php-version-error/

**Comment by willmot** [comment]
@katmoody did we confirm this as user error? If so let's close.

**Comment by katmoody** [comment]
I had waited on a reply but added another update with that plugin link and asked for specific feedback - will update when I see a response ;-)

**Comment by willmot** [comment]
@katmoody going to close this out due to lack of feedback and fact that we're highly confident that BackUpWordPress is correct here.
