### ISSUE TITLE
PHP warnings when proc_open is a disabled function

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1049]
This needs confirmation and further testing. 

I've had multiple tickets with interactions potentially between WordFence and BWP - this was confirmed as a dual issue between the two plugins by a recent ticket with the help of SiteGround's great support team. 

I'm going to set WordFence up on my test site and start testing the settings to see at what point any problem occurs. But I assume there needs to be further testing? 

Most recent ticket referred to above from Intercom: 
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/4338796550

```
Now i have problems with my scans (WordFence). They start but they do not finish (turn during hours without results...)

I mentionned that to the server techs and to Wordfence plugin's tech. The only way to scan with success was to deactivate your plugin, and it fixed the issue. When i reactivate Backup Wordpress, i still have the error. I'll join a printscreen of it.
``` 

![backup](https://cloud.githubusercontent.com/assets/5481211/14147860/2fb61a20-f66b-11e5-9e8a-846fe95b6e88.jpg)
![backupwp](https://cloud.githubusercontent.com/assets/5481211/14147861/300fdc86-f66b-11e5-9362-9ae830803adc.jpg)

**Comment by pdewouters** [comment]
are `exec` and `shell_exec` also disabled? (just curious)

**Comment by katmoody** [comment]
@pdewouters no - but proc_close is disabled as well as a few others I haven't encountered before: 
`dl, passthru, proc_close, allow_url_fopen`

**Comment by willmot** [comment]
Users who have `proc_open` disabled will still be able to use the PHP fallback. At a minimum we just need to silence/avoid the warning.

**Comment by katmoody** [comment]
That's what I thought, but wanted to confirm ;-) Thanks!
