### ISSUE TITLE
Fatal Error: Uncaught Error

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1056]
I'm going to add this to the FTP repo as well, but since it effects the running of the plugin on the full site I wanted to log it here as well. 

```Fatal error: Uncaught Error: Call to undefined function HM\BackUpWordPress\ftp_connect() in /customers/0/e/a/home-business-computing.de/httpd.www/wp-content/plugins/backupwordpress-pro-ftp/inc/FTP.php:164 Stack trace: #0 /customers/0/e/a/home-business-computing.de/httpd.www/wp-content/plugins/backupwordpress-pro-ftp/inc/FTP.php(93): HM\BackUpWordPress\FTP->connect('hbc-backup.disk...') #1 /customers/0/e/a/home-business-computing.de/httpd.www/wp-content/plugins/backupwordpress-pro-ftp/inc/FTPBackUpService.php(449): HM\BackUpWordPress\FTP->test_options(Array) #2 /customers/0/e/a/home-business-computing.de/httpd.www/wp-content/plugins/backupwordpress/classes/class-service.php(136): HM\BackUpWordPress\FTPBackUpService->update(Array, Array) #3 /customers/0/e/a/home-business-computing.de/httpd.www/wp-content/plugins/backupwordpress/admin/actions.php(197): HM\BackUpWordPress\Service->save() #4 /customers/0/e/a/home-business-computing.de/httpd.www/wp-includes/plugin.php(525): HM\BackUpWordPress\edit_schedule_services_submit('') # in /customers/0/e/a/home-business-computing.de/httpd.www/wp-content/plugins/backupwordpress-pro-ftp/inc/FTP.php on line 164```

**Comment by willmot** [comment]
I think this should just be on the FTP repo as it's specific to running that extension.
