### ISSUE TITLE
Create Process Error

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1057]
New error reported. This is NOT affecting the backup currently, though they are tracking that. 

The site DOES show that proc_open is enabled, but I wasn't sure it was actually related to proc_open versus something else? 

`Warning: proc_open(): CreateProcess failed, error code - 5 in D:\Domains\yetmorestuff.net\wwwroot\wp-content\plugins\backupwordpress\vendor\symfony\process\Process.php on line 290`

**Comment by pdewouters** [comment]
Looks like it's `ACCESS DENIED` https://msdn.microsoft.com/en-us/library/ms681382(v=vs.85).aspx

**Comment by katmoody** [comment]
so basically the user doesn't have permissions to use the proc_open command on that server?

**Comment by willmot** [comment]
This error will no longer show for users whom are still able to backup.
