### ISSUE TITLE
MySQLDump and Mysql access errors

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1059]
Unsure if these are errors that need corrected or errors that shouldn't be displayed:

```
mysqldump: Got error: 1044: Access denied for user 'wordpress'@'localhost' to database 'wordpress' when using LOCK TABLES
Connection to mysql failed with message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''
```

**Comment by willmot** [comment]
Those are errors that shouldn't be displayed as it should just fallback.

@katmoody want to start a doc of known errors, that way we can keep track of all these issues that aren't things we're going to fix.

**Comment by katmoody** [comment]
On top of it. 😸

**Comment by katmoody** [comment]
I'm adding this to Trello, by the way - in case you guys want to check it again :D

**Comment by willmot** [comment]
Great, guess we can close this issue?
