### ISSUE TITLE
Deprecated Warning

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1060]
Just added for reference, not sure if these are already listed somewhere? 

```[18-Apr-2016 13:05:00 UTC] PHP Notice:  HM\BackUpWordPress\hmbkp_add_settings_error is <strong>deprecated</strong> since version 3.4! Use add_settings_error() instead. in /home/katsmed1/public_html/bwp/wp-includes/functions.php on line 3662```

**Comment by willmot** [comment]
@katmoody what premium extension did this user have as it's an issue with that extension.
