### ISSUE TITLE
Filesize Warning with no actual Size reported

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1062]
Waiting for a bit more information but wanted to list this (thought there was already one listed but don't see it?)

![capture 20d ecran 202016-04-21 20a 2010 09 58](https://cloud.githubusercontent.com/assets/5481211/14710879/3aff2e30-07a5-11e6-9da9-f80f2383f1b0.png)

**Comment by willmot** [comment]
This was resolved in https://github.com/humanmade/backupwordpress/pull/1052 just waiting for the release of 3.6.1.

@pdewouters know of anything that's holding 3.6.1 up or can we release?
