### ISSUE TITLE
Exclude Parent Themes and Child Themes individually

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1068]
Right now, if you try to exclude a parent theme, the child themes are also excluded. Since usually changes would be made to a child theme (and not the parent theme) it makes sense to allow them to be excluded on an individual basis. This was requested on the forums. 

https://wordpress.org/support/topic/child-theme-folders-cannot-be-included-in-backup?replies=5#post-8385452

**Comment by willmot** [comment]
This is almost certainly this issue: https://github.com/humanmade/backupwordpress/issues/777#issuecomment-122336056
