### ISSUE TITLE
Zip Warning: No such file or directory

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1069]
The backup runs despite this error - but on this ticket, the error is displaying multiple times without referencing any specific files. It's more a nuisance thing. Not positive if it is related to the other issue on nuisance errors?

**Comment by willmot** [comment]
We should be ignoring this error since https://github.com/humanmade/backupwordpress/pull/1001/files#diff-6d46e8fa1a3c5f5e92e2439027dd5b73R109

We'll need to do some testing to figure out whether this is working as it should.

**Comment by willmot** [comment]
Confirmed this is no longer happening.
