### ISSUE TITLE
Ghost backup running

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1070]
The backup process seems to repeat outside of the schedule assigned to it. At first I thought it might be a wp-cron issue, but it doesn't check out as a wp-cron issue, and at least one site in question did have other traffic at the time. 

I'm still tracking info on this - suggestions on potential things to check great but I am hoping to find this is a weird fluke ;-)

**Comment by katmoody** [comment]
One ticket: https://wordpress.org/support/topic/2-weekly-backups-5-minutes-apart?replies=3#post-8417846

**Comment by willmot** [comment]
I'd check whether doing a manual backup also causes multiple backups. That'll tell us whether it's something specific to the automatic backups or not.

I'd also ask him to try an automatic backup with all other plugins deactivated and the default theme to make sure it's not another plugin that's causing crons to run twice or something.

Ultimately though, without a reproducable issue there's not much we can do here, we'd need access to his specific server.

**Comment by willmot** [comment]
@katmoody any more info to help reproduce this? If not going to close.

**Comment by katmoody** [comment]
I wasn't ever able to reproduce this :( Also haven't had another post like it since

**Comment by willmot** [comment]
No worries, going to close but we should re-open if we get a reproducible case.
