### ISSUE TITLE
Rethink display of excluded folder/files from `Your Site` table

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1072]
How excluded folders/files and their corresponding size should be displayed in the `Your Site` table. At the moment it's confusing as it lists excluded resources in the `Your Site` table with their size and a mark that it's been excluded. In this case what will be intuitive to displaying excluded file sizes?

Discussion originated in issue #1058 and move here into a separate issue.

![manage backups wordpress org wordpress](https://cloud.githubusercontent.com/assets/2185972/15856806/e7a919fa-2caf-11e6-8e41-c98f71849ed6.png)

**Comment by dashaluna** [comment]
Other questions / brainstorming:

1. Why excluded folders displaying at the bottom of the list even though originally they where at the top? Excluded files don't seem to change position in the list.
2. I wonder if more visual aid will be helpful to highlight the excluded files - different row background or font colour?
3. For all excluded folders and files, we could display `0 of **` where `**` is the actual size of a folder/file.
4. We could remove excluded folders/files from the `Your Site` table. However, then a user won't be able to navigate those folders - as it's possible at the moment. However, excluded folders are only traversable, but you can't `stop excluding` from there.

**Comment by willmot** [comment]
I think we can definitely improve this.

> Why excluded folders displaying at the bottom of the list even though originally they where at the top? Excluded files don't seem to change position in the list.

That's a side effect of them showing as `0` size as the list is ordered by included filesize. I agree it's super confusing that folders show as `0` whereas files show their original size. I agree that just showing `0 of xx` for files as well would be the simplest fix here.

> I wonder if more visual aid will be helpful to highlight the excluded files - different row background or font colour?

I'd be up for that, having them all at the bottom will help deemphasize them but a different background colour or something could also help. Feel free to have a play around and drop some example screenshots here.

> We could remove excluded folders/files from the Your Site table. However, then a user won't be able to navigate those folders - as it's possible at the moment. However, excluded folders are only traversable, but you can't stop excluding from there.

I think removing them entirely could be confusing as someone might use that table to find a specific file or folder to check whether it's actually excluded or not.

I like the idea of being able to stop excluding from that list but there is a complication there if you were to try to stop excluding a single file / subfolder that is itself inside a parent which is excluded.  For example, if you exclude `wp-content`, then navigate inside it, you couldn't easily `stop excluding` just `wp-content/uploads`.

**Comment by willmot** [comment]
The other thing to mention, even though it's not possible through the current UI. The excludes system is actually based on "exclude rules". In the current UI, excluding a file or folder just adds an exclude rule for that entire path (so you're just excluding that file or folder and all subfolders & files). The list of "currently excluded" is actually list of "exclude rules" rather than a list of all files and folders that are excluded. (Perhaps we should label that more clearly).

In the previous UI and still under-the-hood, the system uses "exclude rules". You can still add exclude rules by defining the `HMBKP_EXCLUDE` Constant in `wp-config.php`. For example you could exclude `*.php`, which would match against every PHP file. If you were to do that then `*.php` would show up under `currently excluded` and all PHP files would be shown as excluded under `Your Site`.

All that to say, it's not really possible to merge those two tables given the current system.

**Comment by dashaluna** [comment]
@willmot thanks for explaining things!

Here are my thoughts:

1. Agree that all excluded files and folders should say `0 of xx`
2. I think grouping all excluded files at the bottom is a good way to separate within the same table.
3. Attaching my idea about visual aid. I wanted something clear, but at the same time without overwhelming or colouring the table too much. I think that might be a good idea. Please bear with the screenshot (my photoshop skills are non-existent). Let's confirm colours and text if that's a go idea. Could even add a note that excluded folders are navigable, but stop excluding can be done in the table above.

![bwp admin - proposed ui](https://cloud.githubusercontent.com/assets/2185972/16052886/32cd10e0-325e-11e6-8430-34ef23b7ddfd.png)

4. > The list of "currently excluded" is actually list of "exclude rules" rather than a list of all files and folders that are excluded. (Perhaps we should label that more clearly).

I think it's good idea to clarify things, however, I'm worried about confusing users! I think only more advanced users or devs need to know that, perhaps? It might be a good idea to refer them to specific section of docs about it (if we have one). So we can add a link with text `Developers learn more about excluded files`. Where they can learn that it's actually `exclude rules` and you can modify them via `HMBKP_EXCLUDE` constant.

What do you think? Let me know what points you agree on and I can start looking at them :)

**Comment by willmot** [comment]
> Agree that all excluded files and folders should say 0 of xx

Great, let's do that 👍

> I think grouping all excluded files at the bottom is a good way to separate within the same table.

That will happen naturally as the table is sorted by filesize, so excluded items with filesize 0 will end up at the bottom.

> Attaching my idea about visual aid.

I'm not convinced that's needed, given they'll all be at the bottom anyway, and we already display the word `excluded` next to each one, what do you think?

> I think it's good idea to clarify things, however, I'm worried about confusing users!

Agreed, we already have some help text in the Help tab, I think we could add a note / link to additional info, but let's leave that as a separate thing to this PR.

**Comment by dashaluna** [comment]
Closing this as PR has been merged it 🎉
