### ISSUE TITLE
Minor: Remove format identification if file/directory included size is 0

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1079]
Creating as a separate issue, so that we can release #1072 sooner.

Remove `B` from `0 B of x KB` in Included Size column, so it's `0 of x KB`.

<img width="1242" alt="screen shot 2016-07-07 at 14 20 10" src="https://cloud.githubusercontent.com/assets/2185972/16654882/affeb782-444f-11e6-9b65-b5a34cdbc3bd.png">

**Comment by willmot** [comment]
This is now done in #1072
