### ISSUE TITLE
Fatal Error on Activation

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1080]
Looks like it's a process-related error? 

`Fatal error: Function name must be a string in wp-content/plugins/backupwordpress/vendor/symfony/process/Process.php on line 1364
`
Here's the link to the wp.org forum post: https://wordpress.org/support/topic/error-activating-7?replies=1

Should hopefully be solved after updating Symfony libraries per #1081 - can close ticket after confirming it is fixed.

**Comment by katmoody** [comment]
Hey @pdewouters since #1081 was closed without updating Symfony libraries, can you let me know what we should do here instead?

**Comment by dashaluna** [comment]
@katmoody how do I test this? I've run a backup with `Run now` and nothing came up in the `php.log` file. Is that the right place to check that?

**Comment by katmoody** [comment]
Not sure on this at all - I'm not familiar with Symfony - would need either @willmot or @pdewouters to weigh in on this one?

**Comment by willmot** [comment]
I haven't been able to reproduce this either and don't know what it could be caused by.

**Comment by dashaluna** [comment]
Marked as `Infrequent Issue`. Closing. Let's open again if it happens with more info.
