### ISSUE TITLE
Update Symfony libraries

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#1081]
We have fallen a bit behind on this as composer.json is frozen at `2.8` , so we'd need to change that to 
```
"symfony/process": "~3.*",
```
then run a `composer udpate`

this is for both Process and Finder

**Comment by willmot** [comment]
symfony 3 requires PHP 5.5.9 so probably not viable at the moment

**Comment by pdewouters** [comment]
ok closing then.
