### ISSUE TITLE
Exclude codedev from final plugin build

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1086]
We've added ` codecov.yml` file in #1082 We need to exclude it from being in the final plugin build that goes to WP plugin repo.

**Comment by dashaluna** [comment]
@willmot not sure where to add that, would you mind looking into it please?

**Comment by pdewouters** [comment]
@dashaluna it's under `grunt/excludes`

**Comment by dashaluna** [comment]
@pdewouters thanks! Let me have a look then :)

**Comment by willmot** [comment]
This was done!
