### ISSUE TITLE
Add hint about how to change the backup directory to FAQ

### ISSUE THREAD

**Issue by COLABORATI** [humanmade/backupwordpress#1091]
I can see no obvious way to change the backup directory. On the WordPress plugin site the first item of the FAQ section is about this and it reads: 
`Backups are stored on your server in /wp-content/backups, you can change the directory.`

The expected sentence that should follow this would explain _how to change the directory_ - unfortunately this sentence is missing. 

Please add this sentence to the FAQ after that sentence above: 
`You can change the backup directory by setting the constant HMBKP_PATH to the desired path in your settings file.`

Thanks.

**Comment by willmot** [comment]
I agree it should be easier to change your backup directory!

**Comment by pdewouters** [comment]
I think there's a ticket to add a UI for that

**Comment by katmoody** [comment]
I am adding more documentation to the Knowledge Base for all the constants as well. The information shouldn't be so hard to find, for sure!

**Comment by katmoody** [comment]
This was merged and can be closed. Additional work in #1103 to add in UI section for better handling in the futuer.
