### ISSUE TITLE
Unable to download file from admin backup listing

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1093]
I've had several reports of folks being unable to download links and am trying to see if there are any commonalities. 

In this ticket, the difference in the two sites the person had was that one was hosted with DreamHost while the other was not. Unsure if that has bearing on it  or not. 

Link to forum post with more information: 
https://wordpress.org/support/topic/cannot-download-backup-1?replies=3

Initial post text: 
I recently installed BackUpWordPress for a new website that I'm running and unfortunately I am unable to download the backup file.

To give a few more details:

> 1) I'm trying to backup both the database and the files.
> 2) On this domain (development-solutions.eu) - I can run a backup no problem, but whenever I try to download it, the plugin redirects me to a non-existing page on my site. This one to be more specific: 
> 3) On another domain (korea-euilo111.com) - I can download the backup file just fine.
> 4) The only difference between these two domains is that one of them (development-solutions.eu) is hosted with DreamHost, via their DreamPress service and the other one (korea-euilo111.com) is hosted with HostGator.
> 
> I'm curious to know if anybody else has encountered this issue and if there is a way to resolve it.

**Comment by willmot** [comment]
@katmoody we'll need access to debug this as it's not clear from what I can see why this wouldn't be working.

**Comment by katmoody** [comment]
I am waiting on access and will pass that on when I have it - is admin access enough or will you need cPanel or FTP?

**Comment by willmot** [comment]
Both ideally 👍

**Comment by katmoody** [comment]
Okay. Will report back when I hear back.

**Comment by willmot** [comment]
@katmoody closing as those backup links now seem to be working.

Aside, I removed the link from the description, best never to post them as anyone could then download that persons backup.
