### ISSUE TITLE
Exclude error.log and debug.log from backups automatically

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1095]
Brought up by @pdewouters - add to default exclusions to exclude error and debug logs automatically.

**Comment by willmot** [comment]
Perhaps we should just auto exclude all filenames ending in `.log`?

**Comment by katmoody** [comment]
I'm going to try tackling this as it looks easy enough to do and I'm already pushing through an update to the exclusions. I'll add this to it.
