### ISSUE TITLE
Character Encoding potential issue

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1096]
We looked into this extensively with a previous (now closed) issue, #978, but there was a review left where the poor guy basically lost a good chunk of his site because he had what looks to be the same issue. 

This is the review post in question: https://wordpress.org/support/topic/failed-when-i-needed-it-most?replies=4#post-8804468

If, as noted by @willmot in the other ticket, it's probably an issue related to the unzipping of the file, I'd like to figure out a way to very clearly spell out the best way to adjust for this if at all possible. 

It won't be something to help this poster, as he is already switching to a static site (poor guy, I feel bad for him) and doesn't want to undergo additional troubleshooting at all. But I do at least want to be able to address this moving forward just in case there's an issue again the future.

**Comment by willmot** [comment]
It would be useful to get a list of some of the foreign image filenames to test with.

**Comment by katmoody** [comment]
I wonder if it would be possible to just set some up on my test site with foreign file names?

**Comment by willmot** [comment]
@katmoody more testing is always good, but, we already have unit tests with foreign filenames and they work fine. We've also used this on lots of sites with unusual characters in filenames, so it should work and has been well tested. To fix we really need a reproducible issue with an exact filename.

**Comment by dashaluna** [comment]
@willmot @katmoody what's the status with this? Shall we close until it happens again with exact file names?

**Comment by katmoody** [comment]
Let's close and open a new issue if we see this come up again, since it likely means a new variation to add to the unusual characters of a specific nature. It seems a fairly isolated issue but important to be aware of it. 

I wonder @willmot - should we have a list of all known issues like this, which have been addressed but still occasionally still show up? If nothing else, for us to refer to? it's hard to know what to search for in Github sometimes in order to search all issues.

**Comment by dashaluna** [comment]
@katmoody good plan. I've created a label `Infrequent Issue`, so hopefully it will be easier to find these kind of issues in the future. Let's try it out and see if it works.

**Comment by katmoody** [comment]
Great idea for the new label! :D
