### ISSUE TITLE
Confusing versions shown when extension updates are available

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#1098]
On the Extensions page, installed extensions are showing a notice that an update is available, even though I'm on the latest version.

<img width="619" alt="screen shot 2016-08-26 at 17 58 40" src="https://cloud.githubusercontent.com/assets/308507/18016921/be9c9a7c-6bc6-11e6-9020-13da36c655c8.png">
<img width="615" alt="screen shot 2016-08-26 at 17 58 50" src="https://cloud.githubusercontent.com/assets/308507/18016922/bebdea1a-6bc6-11e6-9f56-d0b682482ccb.png">

**Comment by dashaluna** [comment]
@willmot can't recreate, is this still happening?

**Comment by dashaluna** [comment]
I've installed and activated the Dropbox extension. Here is what I'm seeing:
<img width="1260" alt="screen shot 2016-09-27 at 11 09 20" src="https://cloud.githubusercontent.com/assets/2185972/18869438/43a1cb98-84a4-11e6-9abe-d698982751e4.png">

@katmoody can you double check if you can recreate this? If not, let's close this. Thanks :)

**Comment by willmot** [comment]
I took a look locally and I actually have this wrong. It's not that it's showing the update when you have the latest version installed. It's that the update plugin message is showing the wrong version number.

Locally I'm running an old version of the Dropbox extension, version `2.1.7`. The Extensions page correctly shows that an update is available, but it's confusing because the "Plugin version" text shown before the update message looks like it's showing my current version, however it's not, it's showing the latest version.

We just need to improve that messaging so it's less confusing.

**Comment by katmoody** [comment]
@willmot - I just added the 'upsell' option text (for the developer bundle section) to the end of that text, didn't change anything else. But you guys can definitely improve on that if you like! It might actually be better to pull a custom excerpt rather than all the text?

**Comment by dashaluna** [comment]
So `Plugin version x.x.x` displays the latest extension version regardless if it's installed or not. How about these text:

```
Latest plugin version x.x.x
(Your) Installed plugin version x.x.x. Update now to latest (x.x.x) version.
```

@willmot what do you think?

**Comment by willmot** [comment]
Perfect 👍

**Comment by dashaluna** [comment]
@willmot I'm going through fixing escaping here as well. Quick question ... why do we need `<span title="<?php echo esc_attr( $extension->modified ); ?>">` on https://github.com/humanmade/backupwordpress/blob/master/admin/extensions.php#L151

It's not being displayed on the front-end page, only in source (hope that makes sense). Is it used for something internally?

**Comment by willmot** [comment]
@dashaluna not following, I see that text on the frontend of the extensions page.

**Comment by dashaluna** [comment]
@willmot sorry! :)

So current HTML generated from that line is:

```
<strong>Last Updated:</strong> <span title="2016-08-26T17:25:35">1 month ago</span>
```
Can we simply have:
```
<strong>Last Updated:</strong> 1 month ago
```
or does `title` attribute from original HTML is used for something? I've checked the display without extra HTML and it doesn't change. I'd go for simplicity if it isn't used anywhere.

Does that make sense?

**Comment by willmot** [comment]
If you hover over the text the `title` attribute shows in a popup. That said, the `span` could probably be an `abbr`.

**Comment by dashaluna** [comment]
I was more asking if we really need that? Or can we remove the exact time on hover?

**Comment by willmot** [comment]
I don't think it's particularly necessary, I'd originally implemented it that way as an accessibility feature, however that may actually have been bad practise: http://www.webstandards.org/2007/04/27/haccessibility/

I vote we remove.
