### ISSUE TITLE
Use of composer could cause issues

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#1101]
see https://core.trac.wordpress.org/ticket/36335

**Comment by willmot** [comment]
I think it's likely https://core.trac.wordpress.org/ticket/36335 is going to be reverted. I'm going to close this as there's no further action at the moment, we can re-open once it lands in core.

I tested running `composer install` with the latest WP Core trunk and all worked correctly.

**Comment by pdewouters** [comment]
There was a Github issue linked in the comments, that might still be relevant to us, that I'll link to here, just in case it comes up, and might save us some time investigating: https://github.com/composer/composer/issues/3852#issuecomment-172844677

> WordPress and two plugins using different Composer's ClassLoader class versions.

For example, another plugin could use a Symfony cmoponent, or the Google SDK which is quite common but use a different autoloader.
