### ISSUE TITLE
Exclude backupwp and other backup folders from backups run

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1105]
In looking through some sites having issues, we find that some sites are having issues with previous backups (from other plugins) not being auto-excluded as they should be. I'll add to this list when I run across these. 

- backupwp (this is sometimes in the uploads folder it looks like?)
- snapshot(s)

**Comment by dashaluna** [comment]
@katmoody are these the names of directories that other backup plugins create?

**Comment by katmoody** [comment]
Hey @dashaluna - These would be subdirectories, usually within wp-content, sometimes within wp-content/uploads/

**Comment by dashaluna** [comment]
@katmoody thanks! I just wanted to double check the exact names of the folders, so I can test. Are those names exactly how other plugins name them?

**Comment by katmoody** [comment]
Those are, yes, @dashaluna :-)

**Comment by katmoody** [comment]
I have noticed that "snapshot" is both single and with an "s" at the end, by the way? Maybe different plugins?

**Comment by dashaluna** [comment]
Also, it doesn't seem to list all matched default exclude rules in the `Currently Excluded` list. For example, here only 1 folder is shown in the list, while `wp-content/wp-snapshots` isn't and it should be.
![backupwordpress - default exclude rules](https://cloud.githubusercontent.com/assets/2185972/18787999/15ba8a6c-819d-11e6-8588-7123e4c99be7.png)

**Comment by katmoody** [comment]
l wonder how it's listed? Is there a variation in the format at all?

**Comment by dashaluna** [comment]
@katmoody Sorry, not sure what you mean?

**Comment by dashaluna** [comment]
@willmot I'm a bit confused. Does `Currently Excluded` table should display all the folder that a user have got that have matched the default exclude rules or just for our plugin?

So in the screenshot above, should `Currently Excluded` table display `wp-content/wp-snapshots` or not?

**Comment by dashaluna** [comment]
@willmot re previous comment, if it is - let's make a new issue as it doesn't seem like a quick fix. So this one is ready for review then. Btw, not sure why travis failed the testes and don't know how to restart it, if you don't mind looking at it?

**Comment by willmot** [comment]
> @willmot I'm a bit confused. Does Currently Excluded table should display all the folders that a user have got that have matched the default exclude rules or just for our plugin?

It just shows user added exclude rules, not any of the defaults.

**Comment by dashaluna** [comment]
@willmot thank you for clarifying. This is ready for PR then.

**Comment by katmoody** [comment]
Hey @willmot - just want to clarify on not being able to list out all the auto-excluded files - is there a way to get that list on request? IE for troubleshooting? And if not, could we consider that as an improvement?

**Comment by willmot** [comment]
It's not possible. We don't know which files will be caught by an exclude rule until we do the backup or list the files on the excludes page. Looping through every file on the entire site to check whether it matches an exclude rule would almost certainly fail due to memory or timeout limits.

**Comment by willmot** [comment]
Instead we likely want to simplify the default exclude rules so that we're just excluding absolute paths rather than patterns. That way we can simply check if the path exists and if so we know it'll be excluded and thus can show it.
