### ISSUE TITLE
Disregarding number of backups set in settings to save

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1106]
From Intercom: 

> Hello. On all of my BackUpWordPress installs, I set the local backups to just retain 1, I have more versions saved remotely via Amazon S3. However, whenever I visit the BackUpWordPress page, it says I have 2 backups saved, which takes up space on my server. Whenever I refresh the page, it deletes the extra backups, but after next scheduled backup occurs, the extra backup reappears. In short, I only need 1 backup retained on the server. Although those are my settings, 2 backups are retained, until I manually refresh the BackUpWordPress page in the WordPress dashboard. Can this be fixed? Thank you

Link to Intercom ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/5572334043

**Comment by dashaluna** [comment]
Tested with `Run now` functionality instead of schedule:

1. Set `Number of backups to store on this server` to 1.
2. `Run now` backup several times.
3. WP admin page displays just 1 latest backup without refreshing the page.
4. Server has got the latest backup as well

Tested with `Once Hourly` schedule:
**results to follow**

**Comment by dashaluna** [comment]
@willmot hm, that's strange the `Once Hourly` didn't run any backups. No errors in the `php.log`. Is there something I'm missing setup wise? Is there a different place I can look at for logs?

**Comment by willmot** [comment]
@dashaluna is cron working locally for other things? Could just be a generic cron failure.

**Comment by willmot** [comment]
@katmoody were you able to reproduce this?

**Comment by katmoody** [comment]
@willmot I could NOT reproduce this locally - I don't have a current Amazon account to test that through (is there a company one I can use for testing like this?). But this is the only person I've seen with this issue. 

I'm wondering if the cache could be in play as a factor here? Basically both backups show until he physically refreshes the page, every time - I'm wondering if there's a cache value that can be looked at on that? I'm not familiar enough with caching to know how to test that :(

**Comment by katmoody** [comment]
Just trying to follow up on this - it is a reproducible issue or should we close it at this point? @willmot @dashaluna

**Comment by katmoody** [comment]
Closing this as we weren't able to reproduce or confirm and I haven't received further issues like this for comparison.
