### ISSUE TITLE
Tune codecov settings

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1107]
Tune in codecov settings so it shows up as a check rather than posting a comment

**Comment by dashaluna** [comment]
@willmot do we need `Project Status` https://github.com/codecov/support/wiki/Commit-Statuses ?

**Comment by willmot** [comment]
@dashaluna I don't know tbh, I'm not particularly familiar with codecov

**Comment by katmoody** [comment]
Is this still needed or can it be closed @willmot or @dashaluna ?

**Comment by willmot** [comment]
I think we should just remove codecov as it doesn't seem to work very well and isn't being used. @pauldewouters I think it's attached with your account?

**Comment by katmoody** [comment]
@pdewouters ^^^

**Comment by katmoody** [comment]
Would removing the https://github.com/humanmade/backupwordpress/blob/master/codecov.yml file be the only real need in removing it from the plugin or are there references in other places that would need to be addressed @pdewouters ?
