### ISSUE TITLE
Extensions page: simplify descriptions

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1123]
Shorten them all down to a single paragraph or so.

**Comment by katmoody** [comment]
Just reposting this from previous ticket so we have it for reference (and because Dasha asked :grin:)
>...the descriptions here are actually pulled from each of the product pages - that's why the text changed when I was updating product information. Is there a way to create a custom excerpt to pull for that instead? That would allow granular control over the content displayed, much like the short description pulled for the WP repo example above?
>
>I'm all for re-writing the product descriptions further as well, but I think we're looking at two different needs here and they each really do need different text - the product page is for people looking for more specific information on each product listing while the description/excerpt is just a short snippet on info on each of them. Thoughts?

**Comment by dashaluna** [comment]
> by @willmot: Agreed best for these to be different text

**Comment by katmoody** [comment]
Just commenting here as I think this just needs to reference the post excerpt instead of the post content. Shouldn't be a hard fix and then we can use the custom excerpts to better finetune them.

**Comment by willmot** [comment]
Makes sense 👍
