### ISSUE TITLE
Extensions page: Highlight WP admin Backups menu item when on Extension page

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1125]

**Comment by sambulance** [comment]
This wasn't in the pipeline for this sprint, but figured it was a quick one I could pick off easily. Also ensures we get an enhancement in this sprint.

PR: https://github.com/humanmade/backupwordpress/pull/1136

**Comment by libby-barker** [comment]
Awesome @sambulance

**Comment by shadyvb** [comment]
Fixed by #1136

**Comment by shadyvb** [comment]
@sambulance Are we supposed to close this one ?

**Comment by libby-barker** [comment]
Hi @shadyvb it should only be closed if it's deployed.

**Comment by willmot** [comment]
@libby-barker "deployed" in this instance means released to the plugins directory I guess.

**Comment by willmot** [comment]
I guess this can be moved into the 3.6.3 release project?

**Comment by mikeselander** [comment]
Looks like this might have been done already? @katmoody should this still be open?

**Comment by katmoody** [comment]
@mikeselander - looks like it was merged in #1136 -- unsure if that was deployed for sure?

**Comment by sambulance** [comment]
This is done and deployed, can be seen by going to `/wp-admin/tools.php?page=backupwordpress_extensions` and seeing that the Backups menu item in the sidebar is highlighted
