### ISSUE TITLE
Updates notice is missing for Extensions on Plugins page

### ISSUE THREAD

**Issue by dashaluna** [humanmade/backupwordpress#1126]
I've tested with older version of Dropbox extension and on Plugins page it didn't display an update notice, as it does for plugins from WP org repo. See screenshot:
<img width="864" alt="screen shot 2016-09-29 at 13 13 54" src="https://cloud.githubusercontent.com/assets/2185972/18953873/61080332-8648-11e6-9e8b-7e7aa1fba67b.png">

**Comment by pdewouters** [comment]
needs to be activated and have a valid licence

**Comment by dashaluna** [comment]
Verified - needs the valid licence to see the updates functionality. It works.
