### ISSUE TITLE
Check contributed function in forums (code review)

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1129]
A user in the WP forums added a function he created that uses a hover color for the background when going in to choose exclusions. I gave it a cursory look before adding it on my own test site (ping me if you need login info so you can check the effect yourself). It might be worth adding anyway, but in the meantime I just wanted the function itself checked by more knowledgeable folks to ensure it complied with WP standards so I could update that topic in the forums. 

```
add_action('admin_head', 'my_custom_backend_css');
function my_custom_backend_css() {
  echo '<style>
#mainwp_backupwp_excluded_content tr:hover,
.hmbkp-exclude-settings tr:hover {background-color: #f2dede !important;}
  </style>';
}
```

Here's a screenshot of the effect on my test site with the function enabled: 
<img width="1074" alt="screen shot 2016-10-06 at 1 31 26 pm" src="https://cloud.githubusercontent.com/assets/5481211/19163264/46998c7e-8bc9-11e6-9434-bd37c5931c84.png">

**Comment by katmoody** [comment]
Here's the link to the forum post: https://wordpress.org/support/topic/one-small-addition-table-rows-hover/

**Comment by katmoody** [comment]
My first pass at reviewing it: 

```add_action( 'admin_head', 'my_custom_backend_css' );
function my_custom_backend_css() {
    echo esc_html( '<style> #mainwp_backupwp_excluded_content tr:hover, .hmbkp-exclude-settings tr:hover {background-color: #f2dede !important;} </style>');
}```

But is adding to the head of the admin page like that the best way to do it?

**Comment by willmot** [comment]
@katmoody you don't want to run it through `esc_html` as the string contains HTML that you don't want to escape.

Other than that, looks fine 👍
