### ISSUE TITLE
Change disk space calculation restriction to warning

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1131]
Per #1063 issue - @willmot said: 

> We should definitely account for excludes when calculating the remaining disk space.
> We could also consider making this a warning only instead of blocking actual backups as well. If there isn't enough space then backups will obviously fail anyway.

So we need to change the restriction upon finding the disk space and make it a warning instead of disallowing access to the plugin settings.

**Comment by sambulance** [comment]
If I'm understanding this correctly, we need to remove the [`disk_space_low()` check in the `is_backup_possible()` function](https://github.com/humanmade/backupwordpress/blob/master/functions/core.php#L414). The error message will still appear at the top of the page, but the rest of the functionality will be available.

Created a PR here: https://github.com/humanmade/backupwordpress/pull/1132

**Comment by libby-barker** [comment]
@willmot I saw the you merged the PR related to this. Has it been tested/deployed?

**Comment by libby-barker** [comment]
NM, I see it's in "Ready for..."

**Comment by willmot** [comment]
> tested/deployed?

I guess "deployed" would mean released in a plugin update?

**Comment by willmot** [comment]
Perhaps we should have a ready for release tag.

**Comment by katmoody** [comment]
Is this all released as of 3.6.3.1? @sambulance

**Comment by sambulance** [comment]
This is deployed.
