### ISSUE TITLE
Start Time configuration in Database Daily & Complete Weekly

### ISSUE THREAD

**Issue by pixcode** [humanmade/backupwordpress#1144]
When you make configuration changes, the start time is not updated for backup. It stays at 20:16 by default

WordPress 4.6.1 & BackUpWordPress 3.6.2

**Comment by katmoody** [comment]
@pixcode - usually this comes down to a caching error - I'm sorry I missed responding to this before. Have you purged any caches and tried again? And are you still having this issue? Thanks!
