### ISSUE TITLE
Connection issues for premium plugins 

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1146]
These are tickets that are on the Drive and Dropbox repos but they're still impacting users and starting to impact more users. I think they're related and they are a high priority to fix at this point. 

On Dropbox: 
https://github.com/humanmade/backupwordpress-pro-dropbox/issues/34

On Drive: 
https://github.com/humanmade/backupwordpress-pro-dropbox/issues/34

tagging @sambulance and @libby-barker since they need worked on asap and integrated into this/next sprint.

**Comment by sambulance** [comment]
Hey @katmoody we already have an issue for this open with the Amazon ticket too: #1139 

Closing in favour of #1139
