### ISSUE TITLE
Version 3.6.3 release

### ISSUE THREAD

**Issue by sambulance** [humanmade/backupwordpress#1147]
The beta version of the release was created and sent out last week - have we had any feedback yet @katmoody? 

PR for release here: https://github.com/humanmade/backupwordpress/pull/1145

**Comment by katmoody** [comment]
@sambulance  -- I noted this in Slack I think but haven't heard back yet from specific folks we targeted (those with the space being configured incorrectly who lost access to their backups) ... I'm checking in with multiple users today to followup ;-)

**Comment by katmoody** [comment]
Okay - I have now heard back from two people with the specific issue noted above who HAVE had success with the beta. :tada:

I did have a few others try it with what I think are file handling issues that are different, but they didn't have any success :( - but we already knew we'd need to target that.

**Comment by katmoody** [comment]
@sambulance we good on closing this one now?
