### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by arnauldb** [humanmade/backupwordpress#1152]
### Description of issue
doesn't backup anymore since the last update.

### Current behavior
I launch the backup process, it says "starting backup", then nothing.

**Comment by katmoody** [comment]
Thank you for creating your issue, @arnauldb - could you provide a bit more information so we can help you troubleshoot more effectively? 
- Do database backups work? (not the complete ones)
- Do files backups work? (again, not the complete ones - create a new schedule to test this if you don't want to edit a current schedule) 
- If files backups don't work, can you exclude the wp-content folder and try again to run the backup? Does it work now? (this step is for testing only)

### Additional questions: 
1. What else was updated, if anything? Any other plugins, themes or WordPress itself?
2. Does the page reload or does the backup just continue to spin or does something else happen? 
3. What other plugins do you have installed on this site? 
4. Where is this site hosted? Is it shared hosting?

**Comment by pdewouters** [comment]
This should be moved to in-plugin support. Closing.
