### ISSUE TITLE
Add PHP 7.x support

### ISSUE THREAD

**Issue by BronsonQuick** [humanmade/backupwordpress#1154]
We should add PHP 7.x support as per a request on Twitter: https://twitter.com/autoentreprise/status/812980073049575424

The best way to start doing this would be to remove php 7.0 from the allowed failures: https://github.com/humanmade/backupwordpress/blob/master/.travis.yml#L25. We should also add in PHP 7.1 for testing and make the tests pass for those too.

**Comment by pdewouters** [comment]
Looking at the tweet, it refers to WPRemote, so closing.

**Comment by BronsonQuick** [comment]
Hah! Total deep from me. Classic holiday mode!
