### ISSUE TITLE
Semantic versioning doesn't support a 4th-level version # causing npm to not install

### ISSUE THREAD

**Issue by mikeselander** [humanmade/backupwordpress#1156]
We currently have a 4-level version #: `3.6.3.1`. This isn't technically correct semantic versioning, generally not a big deal and I see no problem with this. However, `npm` doesn't support 4th-level version #s and will fail on an install since it's not technically semantic.

I propose that we stick to proper semantic versioning to avoid this issue in the future. `3.6.4` is the same as `3.6.3.1` for all intents and purposes. I understand that this is a pretty small nitpick :)

Error received:
```
npm WARN Invalid version: "3.6.3.1"
npm WARN backupwordpress No description
npm WARN backupwordpress No repository field.
npm WARN backupwordpress No README data
npm WARN backupwordpress No license field.
```

**Comment by katmoody** [comment]
That's actually a really good idea. I didn't even know to check for that! :D

**Comment by sambulance** [comment]
Sorry, my fault with the rush to get 3.6.3.1 out quickly as the released 3.6.3 was causing a fatal error and needed a hotfix. The WP plugin version needed to be changed, but the npm version didn't. If you want to make a PR to change this back to 3.6.3 then we can get this pushed through quickly 👍

**Comment by mikeselander** [comment]
OK, I might do that quickly so that others can set up the project anew if need be 👍

**Comment by katmoody** [comment]
So I'm trying to set this up locally and couldn't do the `npm install` - so we didn't get this changed, right? Is it possible to push it through quickly at all? @sambulance @mikeselander ?

**Comment by katmoody** [comment]
I have a PR in #1165 that bumps this up to 3.6.4, as I thought we always go up? When someone has a chance to go through this feel free to do so. I'm still not at all familiar with doing anything via SVN though 😁

**Comment by mikeselander** [comment]
I'm not sure we'd want to bump the version on the .org repo without an actual change if that's what you're thinking of?

**Comment by katmoody** [comment]
No, @mikeselander - I just wasn't sure I actually changed each of the places I would need to change to bump up the version? I was going to work on some other stuff too and see if all of it together or added to others' work would be in the next version.

**Comment by willmot** [comment]
@katmoody I'd recommend just temporarily changing the version in your local `package.json` file for now, as @mikeselander we don't want to bump the version until we have stuff to release. Also to bump the version we use `grunt build` as part of the release to wp.org, see https://github.com/humanmade/backupwordpress/wiki/Releasing-to-wp.org

**Comment by katmoody** [comment]
@willmot - that's what I did. I just thought I would use the minor changes to test using the Command Line for handling Git instead of the GitHub desktop version. Does that PR need to be gotten rid of now?

**Comment by katmoody** [comment]
Okay - so I went ahead and closed the PR, deleted the associated branch, and disconnected that PR from this issue. Next time we push an update this will be easy to add in to correct.
