### ISSUE TITLE
Extensions screen/titling

### ISSUE THREAD

**Issue by mikeselander** [humanmade/backupwordpress#1159]
### Description of issue
The extension titles are rather confusing and the difference between the tiers is similarly confusing.

**Hanging points where I got confused:**
* Multisite is kind of a "reserved" word and means something very different in the admin context than "Multiple-site license"
* There are multiple tiers of the same addition displayed which led me to think that one was for multisite installs and one was for single-site installs
* The titles are inconsistent: one says "Multiple Site" and others say "Multisite"

I would recommend combining all of the same extensions and showing the dispirate tiers within that one block. So, you'd end up with one block for Dropbox, one for Azure, etc. This would make it far more clear.

**Comment by katmoody** [comment]
While the extensions page is being pulled out in favor of concentrating on the site's funnel first, I think @mikeselander's points were on point. 

1. Multisite is kind of a "reserved" word and means something very different in the admin context than "Multiple-site license" -- **Important note - I'm changing over all the titles in light of this and your other points.**
2. There are multiple tiers of the same addition displayed which led me to think that one was for multisite installs and one was for single-site installs -- **I think this is a straight-up presentation issue and agree it needs further attention. We'll be looking at it more closely when we come back to the extension page in the future.**
3. The titles are inconsistent: one says "Multiple Site" and others say "Multisite" -- **Updated these and going to have a look over them again to ensure I didn't miss any of them. Thanks so much for the insight!**
