### ISSUE TITLE
Extensions screen: Mid-sized blocks column layout

### ISSUE THREAD

**Issue by mikeselander** [humanmade/backupwordpress#1160]
### Description of issue
Between 1100 and 1200 pixels the columns for extensions get really pinched, I would recommend keeping these in a vertical layout up to 1200 pixels.

![image](https://cloud.githubusercontent.com/assets/3021494/21813060/3caddaf8-d755-11e6-8294-fe1047205580.png)

**Comment by katmoody** [comment]
I'm closing this because we've pulled the extensions out for now and when it's reintroduced we will have reconsidered the UI and design.
