### ISSUE TITLE
Incorrect Site Root Path configured

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1166]
I'm unsure if this is in addition to or separate from #1150 but think I've been able to find a contributing factor behind the spinning wheel of doom that impacts finding the site size correctly. 

On the sites in question, the `ABSPATH` and `SITE ROOT` paths are the same, except there is not a final trailing slash on the `SITE ROOT`- so the plugin is misreading that site root path and is unable to find the site info as a result. When I use the constant to define the root path, the site size is able to be calculated again.

I looked through the different classes and think I found where the root and abspath are both set, but I must be missing something as I don’t see a reason why this might happen offhand. Unless it's something to do with the `untrailingslashit` that's on line 126, since that removes the trailing slash?

FYI - I think the different site paths are configured here, starting around line 106-126: https://github.com/humanmade/backupwordpress/blob/master/classes/class-path.php

**Comment by willmot** [comment]
Out of interest, if you manually define `HMBKP_ROOT` to the site root without the trailing slash does it still not work (like you'd expect)?

**Comment by katmoody** [comment]
It didn't when I left the trailing slash off during testing for the one site I changed it for myself. But it wasn't until I compared them that I realized that they were slightly different.

**Comment by katmoody** [comment]
Further reviewing some tickets, @willmot, and I note that even when the site size IS able to be configured, that trailing slash is absent. I think this might be an inability to read the site root path correctly, maybe because of the recursive symlinks, maybe not. I'm still waiting to see if specifying the root path works for a few other folks. I'll report back with any updates.

**Comment by katmoody** [comment]
I wasn't able to glean more information about this. It has helped some users to add the definition, and for others it has helped us find the real issue at the heart of their backups not working. I don't know if this is contributing to the symlink issue we know about in #1150 or causing it, but it definitely pushes the process more quickly into a timeout failure.

**Comment by willmot** [comment]
I think let's close this, without a reproducible issue we don't have anything concrete we can do to fix.
