### ISSUE TITLE
Ability to perform bulk actions on backups

### ISSUE THREAD

**Issue by janefw** [humanmade/backupwordpress#147]
Hello,
    I have been using your plugin for a long time on many sites and I have to say it's one of the best plugins for wordpress.
    Can you please add a feature in your future updates that you can select all backups at once with a check box and delete all backups with one delete button instead of having to delete several backups one by one?
    This is a missing feature and should be there.
    Thanks and regards,

**Comment by willmot** [comment]
Closing as no traction on this.
