### ISSUE TITLE
Ability to change the backup path through wp-admin

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#156]

**Comment by willmot** [comment]
I'm not actually convinced this is a good idea. The only real reason to change your backups directory would be to change it to be somewhere non-web accessible. @pdewouters @katmoody what do you think?

**Comment by pdewouters** [comment]
I'm not convinced either.

**Comment by willmot** [comment]
My concern is that we'll get a lot of people trying to do this without really understanding what they're doing or why and thus generate ourselves a bunch of support.

Going to close but @katmoody if you feel strongly do chime in :+1:

**Comment by katmoody** [comment]
I think being able to do it through the wp-config.php file is okay ... my concern is the same as @willmot - if you make it too easy, people might change it without understanding exactly what they're changing. 

I like the idea but think it would be too easy to abuse and def lead to more support :( - unless there were a way to have an 'advanced' tab for stuff like this in the future? Where variables could be set without having to have them in the wp-config, but it wouldn't be available without clicking through? I like that idea?

**Comment by willmot** [comment]
>  Where variables could be set without having to have them in the wp-config, but it wouldn't be available without clicking through? I like that idea?

I'm ultimately not sure that would provide much benefit over defining Constants in your `wp-config.php`.
