### ISSUE TITLE
Out of memory error in File Fallback

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#207]
````
Fatal error: Out of memory (allocated 35389440) (tried to allocate 4168 bytes) in /var/www/parijsonline.nl/www/cms/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php on line 1013
````

Is storing full SplFileInfo objects in memory the issue?

**Comment by pdewouters** [comment]
Is this related to PclZip? The line number doesn't match anymore

**Comment by willmot** [comment]
It wasn't possible to use DirectoryIterator on some older versions of PHP 5.2 as it didn't support the ability to follow symlinks.

Since we switched to 5.3 it's no longer relevant 👍
