### ISSUE TITLE
Fatal Error in RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#209]
```
Fatal error: Uncaught exception \'UnexpectedValueException\' with message \'RecursiveDirectoryIterator::__construct(/,/): Access is denied. (code: 5)\' in D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php:978
Stack trace:
#0 D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(978): RecursiveDirectoryIterator->__construct(\'/\', 512)
#1 D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(819): HM_Backup->get_files()
#2 D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(753): HM_Backup->zip_archive()
#3 D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php(619): HM_Backup->archive()
#4 D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\classes\\schedule.php(518): HM_Backup->backup()
#5 D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\admin\\actions.php(65): HMBKP_Scheduled_Backup->run()
#6 [internal function]: hm in D:\\www\\avmcoaching.nl\\www\\blog\\wp-content\\plugins\\backupwordpress\\hm-backup\\hm-backup.php on line 978
```

**Comment by olcay** [comment]
<pre>Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(E:/HostingSpaces/olcybyry/klinika.gen.tr/wwwroot,E:/HostingSpaces/olcybyry/klinika.gen.tr/wwwroot): Access is denied. (code: 5)' in E:\HostingSpaces\olcybyry\klinika.gen.tr\wwwroot\wp-content\plugins\backupwordpress\classes\class-backup.php:1136
Stack trace:
#0 E:\HostingSpaces\olcybyry\klinika.gen.tr\wwwroot\wp-content\plugins\backupwordpress\classes\class-backup.php(1136): RecursiveDirectoryIterator->__construct('E:/HostingSpace...', 4608)
#1 E:\HostingSpaces\olcybyry\klinika.gen.tr\wwwroot\wp-content\plugins\backupwordpress\classes\class-backup.php(978): HM\BackUpWordPress\Backup->get_files()
#2 E:\HostingSpaces\olcybyry\klinika.gen.tr\wwwroot\wp-content\plugins\backupwordpress\classes\class-backup.php(877): HM\BackUpWordPress\Backup->zip_archive()
#3 E:\HostingSpaces\olcybyry\klinika.gen.tr\wwwroot\wp-content\plugins\backupwordpress\classes\class-backup.php(714): HM\BackUpWordPress\Backup->archive()
#4 E:\H in E:\HostingSpaces\olcybyry\klinika.gen.tr\wwwroot\wp-content\plugins\backupwordpress\classes\class-backup.php on line 1136</pre>

I think it is not fixed. Thanks.

**Comment by owaincuvelier** [comment]
Hi @olcay,

Thanks for reaching out. This is a bug with IIS servers. We currently have an open ticket for this here: https://github.com/humanmade/backupwordpress/issues/738

**Comment by pdewouters** [comment]
I hope that this will fix all these errors https://github.com/humanmade/backupwordpress/pull/743
