### ISSUE TITLE
Backup download leads to 404 page.

### ISSUE THREAD

**Issue by kazkat308** [humanmade/backupwordpress#298]
About 2weeks ago, I was able to download backup file without any problem but since about a week ago, started to leads to 404 page when I click "download". Please help. Thank you.

**Comment by willmot** [comment]
Would really like to get to the bottom of why wp-cron.php was returning a 404 though, that could well be a bug on our end.

**Comment by owaincuvelier** [comment]
I have another [report](https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/701765965) of download links returning a 404 error.

**Comment by willmot** [comment]
@owaincuvelier ever get to the bottom of this? Is it safe to close this one out now?

**Comment by owaincuvelier** [comment]
@willmot we can close. It's not an issue with BWP.
