### ISSUE TITLE
Add a field in the settings for schedule name. Display field as tab title.

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#351]
Add a new field to the 'add schedule modal'. This way users can give the schedule a unique name. 
Provide a default name ( "Files weekly 1",2,3...)

Other  benefit is that we don't need to store schedule names as hardcoded strings for internationalization anymore.

**Comment by libby-barker** [comment]
@pdewouters updating the name of this issue from "add schedule name field" to "add a field in the settings for schedule name. display field as tab title"

**Comment by pdewouters** [comment]
wontfix
