### ISSUE TITLE
Default schedules are being added again after being deleted

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#484]
From a user:

> When I log into WordPress to download the backup, I’ve discovered on more than on occasion that there are other backups I didn’t request, including daily database backups and weekly file/database backups. When I find them, I delete the schedules for these unwanted backups and they disappear from the list. But sometimes they mysteriously reappear. It seems that this might be happening after I update the plugin.
- [ ] Needs investigating / reproducing

**Comment by ucavus** [comment]
I experienced something similar. Hit the delete link on every schedule and, after the last was deleted, the defaults were recreated.
