### ISSUE TITLE
Plan out what documentation we need

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#526]
Support area may need a bit of a rethink. 

- [x] Maybe the FAQ can be made into different support pages?
- [x] dropbox
- [x] google drive
- [x] amazon
- [x] azure
- [x] rackspace
- [x] dreamobjects
- [x] FTP: SSH2 PHP Extension required for BWP to FTP Extension
- [x] Troubleshooting guide. This will include debugging backups.
- [x] How to enable support
- [x] Scheduling & wp cron issues/explanation.
- [x] Lost licences & downloads.
- [x] PCLZIP_ERR_READ_OPEN_FAIL (-2).
- [x] disk quota.
- [ ] PHP system memory limit.

**Comment by willmot** [comment]
@pdewouters yep makes sense

**Comment by pdewouters** [comment]
Added a Trello card
