### ISSUE TITLE
Ability to pause/disable schedule

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#533]
Would be nice to have a pause button for schedules. and a pause all schedules.

**Comment by willmot** [comment]
Have we ever had any user requests for this?

It's pretty easy to achieve the same affect by just switching the schedule to manual.

I'm +1 for closing as wontfix.

**Comment by willmot** [comment]
Closing as wontfix, feel free to re-open if there's appetite to do it though.
