### ISSUE TITLE
Choose a better name & domain name

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#544]
- http://bwp.hmn.md isn't a nice domain name, not memorable.
- We can't have http://backupwordpress.com as it breaks trademark.
- We probably shouldn't even be using the name backupwordpress as it includes the word WordPress.

@owaincuvelier to research existing plugin name and domains as a starting point.

**Comment by willmot** [comment]
Re-opening for again for discussion.

My current favourite option is `WP Backup` / `wpbackup`

**Comment by willmot** [comment]
Our twitter is already https://twitter.com/wpbackups

http://wpbacku.ps is available.

Maybe we should try it out for a bit and see how it feel.s

**Comment by katmoody** [comment]
From a branding standpoint, having something across social channels AND domain name is best, but it can vary so long as they are uniform. 

FYI - FB's URL for the plugin is http://fb.me/wpbackups too as it was actually the best option available.

**Comment by willmot** [comment]
I bought http://wpbacku.ps

**Comment by willmot** [comment]
I'm fine with this happening, but needs someone to spearhead

**Comment by katmoody** [comment]
@willmot - can we work on a list of what we'd need to do? Maybe decide on a timeline for implementing? Do we just need to change nameservers or would we need someone from the server team to do some stuff as well?
