### ISSUE TITLE
Display a warning if not enough space

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#615]
I think we should show a persistent admin notice "Insufficient space for storing backups in selected path" Please make space by deleting files, deleting old backups, excluding files or set a different path for the backups folder"

We're already displaying remaining space.
https://github.com/humanmade/backupwordpress/pull/600

**Comment by pdewouters** [comment]
We can detect if a user is on cPanel and use their API
http://stackoverflow.com/a/23141107/285564

**Comment by willmot** [comment]
Yeah that would be slick

**Comment by owaincuvelier** [comment]
We should disable 'run now' and schedules if this notice appears as well

**Comment by pdewouters** [comment]
dreamhost doesn't use cPanel - do we have an account on a shared host that uses cPanel?
