### ISSUE TITLE
Rewrite the phpDocumentor bash script

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#622]
Basically, the premise of the phpDocumentor script is to automatically regenerate the PHP Doc HTML on new commits to the master branch. It will automatically push the generated documentation to the `gh-pages` branch which is responsible for the https://humanmade.github.io/backupwordpress/ website.

Right now the script is erroring so we can disable it until this issue is fixed.

**Comment by willmot** [comment]
@pdewouters is this still planned or shall we close out?

**Comment by pdewouters** [comment]
would be nice to have

**Comment by willmot** [comment]
Going to close this out as it doesn't really fit into our current plans. Can always re-open later.
