### ISSUE TITLE
Directory size display with subdirectory excluded.

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#630]
![screen shot 2014-12-08 at 16 57 41](https://cloud.githubusercontent.com/assets/1263370/5343120/89b97730-7efb-11e4-82a2-a4b162e713f3.png)

Above is the directory size of wp-content. What is not clear is that there is a subdirectory which has been excluded.

It would be good is if we indicate the size of the directory after excludes are taken into account. See below for example

![screen shot 2014-12-08 at 17 03 26](https://cloud.githubusercontent.com/assets/1263370/5343190/2d33d446-7efc-11e4-9a04-8fbbf1cfeb67.png)

**Comment by willmot** [comment]
I think those sizes should be the size minus excludes, that way users can see the numbers going down as they exclude things. We should put the total size in the title attribute with a sentence explaining that.

**Comment by willmot** [comment]
Also see https://github.com/humanmade/backupwordpress/pull/873

**Comment by willmot** [comment]
Implemented in https://github.com/humanmade/backupwordpress/pull/1010

**Comment by willmot** [comment]
This was implemented in #1010. Any new issues can be opened separately.
