### ISSUE TITLE
Extract out the schedule monitoring from Schedule class

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#631]
The `HMBKP_Scheduled_Backup` class has too many responsibilities.

One functionality we can abstract out is the status monitoring.

Schedules could publish status to subscribed objects using the Observer pattern. We could have a single `Backup_Monitor` class or whatever that would have a collection of all running backups, and handle status changes. It would maybe make it easier to have parallel running backups with Backdrop.

Why are we writing status to a file? Could it not be a DB option?

Ha, actually suggested by Scrutinizer 
https://scrutinizer-ci.com/g/humanmade/backupwordpress/code-structure/master/class/%2Bglobal%5CHMBKP_Scheduled_Backup

Thoughts? @willmot

**Comment by willmot** [comment]
Also see #667.

> Why are we writing status to a file? Could it not be a DB option?

Because DB connections can go away, generally the FS is more reliable.

**Comment by willmot** [comment]
Done as part of https://github.com/humanmade/backupwordpress/pull/936
