### ISSUE TITLE
Should build stuff be in a separate repo

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#635]
All the commits made to CI config files, unit tests, etc.. are polluting the plugin history, plus most often we'd want to have the config changes added to all branches when committed.

Could we have a `build` submodule or similar? This would actually be similar to the previous setup with `backupwordpress.dev` and the plugins as submodules!

What were the disadvantages of that setup? ( for me )

- deeply nested submodules: project > plugin > libraries > libraries used in libs OMG
- developing in the submoduled plugins is confusing to me.

Is there a better way?

**Comment by willmot** [comment]
@pdewouters anything else that needs doing here?

**Comment by pdewouters** [comment]
Not so sure about this anymore. Any build related commits can be squashed together when a PR is opened.
Also, this cleans up the build process a bit https://github.com/humanmade/backupwordpress/pull/893

Closing for now.
