### ISSUE TITLE
Support Center subpage

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#638]
Letting my amazing design instinct loose on the sub-menu pages. Will play around with third levels as well just in case.

![screen shot 2014-12-11 at 18 16 15](https://cloud.githubusercontent.com/assets/1263370/5399322/d14ad1da-8161-11e4-9110-b757fd5b6ee6.png)

Better scale.

![screen shot 2014-12-11 at 18 18 01](https://cloud.githubusercontent.com/assets/1263370/5399354/1852e11c-8162-11e4-9b1b-487ba582c0b0.png)

**Comment by owaincuvelier** [comment]
No, I've got changes I'll push.

**Comment by willmot** [comment]
@owaincuvelier any update on this?

**Comment by owaincuvelier** [comment]
Won't fix. Going to close. It works fine. We should overhaul the documentation centre in future. I think at the time when we have purchasing of premium extensions through BackUpWordPress free, we can revisit this again.
