### ISSUE TITLE
Create filters for all configurable constants

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#656]
In some contexts, and for personal preference, it would be nice to have filters for the configurable constants. Can we do:
`define( 'CONSTANT', apply_filters( 'CONSTANT_FILTER','value' );`

For example in the tests, we are calling `constant_changes` which should probably be a protected method. Could use a filter instead.

Anyway, very low priority

**Comment by willmot** [comment]
@pdewouters is this still relevant?

**Comment by pdewouters** [comment]
not really solving anything.
