### ISSUE TITLE
Null characters in SQL script

### ISSUE THREAD

**Issue by hdeadman** [humanmade/backupwordpress#659]
I am using a Google Calendar plugin that puts data in the wp_options table. One of the values contained two  null characters (which each showed up as "00" when viewed with a hex editor). These caused the script to fail when it was run and it caused the file to be stop loading at the first null character when opened in certain text editors. I think it would be safe to strip out (remove) any of those characters that managed to work their way into the data.

**Comment by willmot** [comment]
What plugin were you using, keen to reproduce the issue.

I don't have a solid grasp of how null characters should be handled but I'm not sure stripping them is the right approach, aren't they possibly valid data in some circumstances?

Another reminder that we need unit tests for our DB stuff.

**Comment by hdeadman** [comment]
I don't think null characters have any legitamate use in a text column. They are illegal in XML and they mess up lots of editors and text processing code. This person was having problems with them and his solution was just to remove them:
http://blogs.visigo.com/chriscoulson/removing-null-characters-0x00-from-values-in-sql-server/
Here is another post of someone having problems with them:
http://bi-logger.blogspot.com/2011/07/sql-server-identifying-control.html
I can't find any way to escape them in a sql script so I would say it's safe to remove them from text data. As-is the script isn't going to work if it contains hexa-decimal null 0x00.

The plugin I am using is the following: 
https://wordpress.org/plugins/google-calendar-events/

I extracted the portion of the SQL script that contained the null characters and uploaded it here:
https://gist.github.com/hdeadman/18dfc16bc4fe6624055c
Note the nulls didn't actually make it in there, they don't survive a copy and paste.  

![image](https://cloud.githubusercontent.com/assets/1556777/5593593/c193e7f0-91e6-11e4-9b89-7a7c1b1ae0c1.png)

**Comment by willmot** [comment]
Closing in light of #835
