### ISSUE TITLE
[ all addons ] Move connections settings to be global

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#662]
We should save the different cloud services connection settings globally instead of per schedule.  We can keep the folder name setting per schedule though.
This would need to be a separate admin page probably, where each addon adds a tab.

Although the current way of copying from an existing schedule seems to work ok. Just might be easier to manage all in one place, and only have one place to update if an email address changes,...

**Comment by willmot** [comment]
👍

**Comment by willmot** [comment]
@pdewouters is this still relevant? Does it make sense to have it on this repo?

**Comment by pdewouters** [comment]
no, we can close it. currently it copies settings to the new schedule
