### ISSUE TITLE
IIS: Folder size not displayed.

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#672]
![screen shot 2015-01-08 at 14 32 20](https://cloud.githubusercontent.com/assets/1263370/5663862/5feec760-9743-11e4-8170-070bbe1e648d.png)

**Comment by owaincuvelier** [comment]
https://github.com/humanmade/backupwordpress/pull/719

**Comment by willmot** [comment]
This was fixed by #719
