### ISSUE TITLE
IIS: Misreported backup size

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#673]
Completed backups are about 7MB in this example, displayed size is 1MB.

Related? #672

![screen shot 2015-01-08 at 14 32 17](https://cloud.githubusercontent.com/assets/1263370/5663866/6efef05e-9743-11e4-88b6-c42f4e46da02.png)

**Comment by owaincuvelier** [comment]
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/633958488

**Comment by owaincuvelier** [comment]
https://github.com/humanmade/backupwordpress/pull/719

**Comment by owaincuvelier** [comment]
Fixed in https://github.com/humanmade/backupwordpress/pull/719

**Comment by pdewouters** [comment]
great work!
