### ISSUE TITLE
Ensure we only show backslashes when displaying directory paths

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#674]
![screen shot 2015-01-08 at 14 32 35](https://cloud.githubusercontent.com/assets/1263370/5663884/98560e7e-9743-11e4-8cfe-46853165ab37.png)

**Comment by willmot** [comment]
This is actually correct as Windows supports both frontslashes and backslashes, however it would be neater to normalise to backslashes.

**Comment by willmot** [comment]
Fixed by https://github.com/humanmade/backupwordpress/pull/874
