### ISSUE TITLE
MySQL SET OPTION is deprecated

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#676]
Our use of it is causing MySQL errors like this one: https://wordpress.org/support/topic/urgent-help-please-7?replies=5#post-6415512

See http://bugs.mysql.com/bug.php?id=66765 & http://dev.mysql.com/doc/refman/5.1/en/set-statement.html

Instead we should just use `SET`

**Comment by willmot** [comment]
@pdewouters I've added this one to the 3.1 milestone as it's pretty important.

`SET OPTION` was deprecated in MySQL 5.1 and completely removed in 5.6 so this is causing PHP database dumps to fail for users on 5.6.

**Comment by pdewouters** [comment]
Where are we using that command?

**Comment by willmot** [comment]
hmm, good point.

I may have misdiagnosed the issue in that forum thread. Not sure now.

**Comment by pdewouters** [comment]
This might provide a solution if user can install/update server software or get his hosting provider to do it
http://www.markomedia.com.au/mysqldump-mysql-5-6-problem-solved/

**Comment by pdewouters** [comment]
Fix confirmed

**Comment by pdewouters** [comment]
Let's catch and fallback to `mysqldump_fallback`

**Comment by willmot** [comment]
This will be resolved with #835
