### ISSUE TITLE
Site size isn't refreshed when adding a new file

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#677]
I added a large video file to my local dev site, but it is not getting indexed.

**Comment by willmot** [comment]
The site size is auto refreshed once per week, you can force a refresh by clicking excludes, hovering over a directory size and clicking the refresh icon. (We should maybe add the same click to refresh functionality to the main site size shown in the schedule sentence.

**Comment by willmot** [comment]
Closing as a duplicate of #784
