### ISSUE TITLE
Error thrown when uploading to Google Drive

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#678]
Edit: After further testing, the error is only thrown when the backup is sent to Google Drive.

![screen shot 2015-01-12 at 15 04 51](https://cloud.githubusercontent.com/assets/1263370/5704790/832476ea-9a6c-11e4-924f-a645d4af43b1.png)

**Comment by owaincuvelier** [comment]
So, when it comes to uploading the backup to Google Drive, it gets as far as creating the destination folder, and then times out before the upload to GD can be completed.

**Comment by owaincuvelier** [comment]
Current suspicion: Maybe related to size of a backup. Smaller sized backups upload without issue, larger backups - around the 2GB size, in this example, are failing.

**Comment by owaincuvelier** [comment]
I think this might be due to the time it takes for his server to upload the Google Drive. I think I can close this out. Any thoughts @pdewouters @willmot before I do?

**Comment by pdewouters** [comment]
@owain yes, when testing locally I also have time outs on large files

**Comment by owaincuvelier** [comment]
closing.
