### ISSUE TITLE
Deleting BWP throws fatal error

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#679]
```Fatal error: Call to undefined function hmbkp_path() in C:\inetpub\wwwroot\wordpress\wp-content\plugins\backupwordpress\classes\class-schedule.php on line 87```.

Theres here: https://github.com/humanmade/backupwordpress/blob/master/classes/class-schedule.php#L87

**Comment by owaincuvelier** [comment]
First tested on IIS, but throws same error locally.

**Comment by owaincuvelier** [comment]
Hotfix was adding ```require_once( HMBKP_PLUGIN_PATH . 'classes/class-hmbkp-path.php' );``` on the line below.

https://github.com/humanmade/backupwordpress/blob/master/uninstall.php#L28

**Comment by pdewouters** [comment]
thanks, released a new version
