### ISSUE TITLE
Silence the `zip` unreadable file warning

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#681]
Currently if ZIP is installed on the server but PHP doesn't have permission to use it, it spits out an error when it falls back to the next level down. 

We should hide the error as there isn't much a user could do about the problem.

**Comment by owaincuvelier** [comment]
To reproduce:

* chmod the ```usr/bin/zip``` folder to 000. 
* run backup
* wait
* spits error ```sh: 1: zip: Permission denied
 HMBKP_SUCCESSsh: 1: zip: Permission denied
 HMBKP_SUCCESS```

**Comment by willmot** [comment]
Naise, should be an easy fix.

**Comment by willmot** [comment]
This is actually the warning `zip` spits out if it encounters an unreadable file. We should just ignore the error as it's useless to the user.

**Comment by willmot** [comment]
These are now silently ignored since #1001
