### ISSUE TITLE
Possible MySQL crash could be caused by file sizes transient insert

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#685]
http://forum.ait-pro.com/forums/topic/backupwordpress-plugin-causes-wp-admin-htaccess-to-be-deleted/#post-20551

**Comment by willmot** [comment]
Good find, we should post there once we fix it.

**Comment by pdewouters** [comment]
> The maximum size of a BLOB or TEXT object is determined by its type, but the largest value you actually can transmit between the client and server is determined by the amount of available memory and the size of the communications buffers.

Could we maybe run the directory scanner in batches so that we don't end up with a huge string to write to the database?

**Comment by willmot** [comment]
Yep see #585

**Comment by willmot** [comment]
This is fixed buy #1008
