### ISSUE TITLE
Don't stomp on errors encountered when zipping the database

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#694]
_From @owaincuvelier on June 29, 2014 8:59_

This was reported by a user.

> I’ve been reading through the zip() function in hm-backup.php. There looks to be a coding error which could suppress an error return from zip and attempt to carry on regardless.

```
    /**
     * Zip using the native zip command
     */
    public function zip() {

        $this->archive_method = 'zip';

        $this->do_action( 'hmbkp_archive_started' );

        // Zip up $this->root with excludes
        if ( $this->get_type() !== 'database' && $this->exclude_string( 'zip' ) )
            $stderr = shell_exec( 'cd ' . escapeshellarg( $this->get_root() ) . ' && ' . escapeshellcmd( $this->get_zip_command_path() ) . ' -rq ' . escapeshellarg( $this->get_archive_filepath() ) . ' ./' . ' -x ' . $this->exclude_string( 'zip' ) . ' 2>&1' );

        // Zip up $this->root without excludes
        elseif ( $this->get_type() !== 'database' )
            $stderr = shell_exec( 'cd ' . escapeshellarg( $this->get_root() ) . ' && ' . escapeshellcmd( $this->get_zip_command_path() ) . ' -rq ' . escapeshellarg( $this->get_archive_filepath() ) . ' ./' . ' 2>&1' );

        // Add the database dump to the archive
        if ( $this->get_type() !== 'file' && file_exists( $this->get_database_dump_filepath() ) )
            $stderr = shell_exec( 'cd ' . escapeshellarg( $this->get_path() ) . ' && ' . escapeshellcmd( $this->get_zip_command_path() ) . ' -uq ' . escapeshellarg( $this->get_archive_filepath() ) . ' ' . escapeshellarg( $this->get_database_dump_filename() ) . ' 2>&1' );

        if ( ! empty( $stderr ) )
            $this->warning( $this->get_archive_method(), $stderr );

        $this->verify_archive();

    }
```
>The problem is in the ‘Add the database dump to the archive’ section. If $stderr has previously been set to something going wrong in either of the with/without excludes sections it will then get cleared when the adding of the database dump is attempted. Instead, the adding database dump routine should test also for $stderr being empty. This will allow any errors from the zip operations before the database adding to be preserved down to the error handler at the bottom of the screen shot.

_Copied from original issue: humanmade/hm-backup#66_

**Comment by willmot** [comment]
We need to fix this, this explains why we sometimes see situations where the backup contains only the database and no errors have been reported. The errors are being overwritten when we add the database to the zip.

**Comment by pdewouters** [comment]
We add the database first now.

**Comment by willmot** [comment]
Ah good catch, so the opposite is now true, errors encountered when adding the database will be lost when we try to add files below.
