### ISSUE TITLE
get_home_path returns an incorrect path when wp-config is stored outside site root

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#695]
_From @willmot on March 26, 2014 13:52_

In https://github.com/humanmade/hm-backup/commit/3e213ac2bbd06d02383ed5290d6475cc1bed0c36 we introduced the following as a workaround for WordPress MS installs where WordPress is installed in a subdirectory. See https://github.com/humanmade/backupwordpress/pull/260 a deeper explanation.

```php
if ( ! file_exists( ABSPATH . 'wp-config.php' ) ) {
	$home_path = trailingslashit( dirname( ABSPATH ) );
}
```

However this broke standard WordPress installs where `wp-config.php` is stored outside of site root. See https://github.com/humanmade/hm-backup/commit/3e213ac2bbd06d02383ed5290d6475cc1bed0c36#commitcomment-5802989.

_Copied from original issue: humanmade/hm-backup#64_

**Comment by willmot** [comment]
We really need unit tests to ensure `HM_Backup::get_home_path()` works correctly in all situations.

The various setups we need to support are:

#### Standard WordPress install

* `ABSPATH` === webroot
* `wp-config.php` in `ABSPATH` 
* `site_url()` & `home_url()` === example.com

`get_home_path()` should return `ABSPATH`.

#### Standard WordPress install, wp-config above webroot

* `ABSPATH` === webroot
* `wp-config.php` in `dirname( ABSPATH )`
* `site_url()` & `home_url()` === example.com

`get_home_path()` should return `ABSPATH`.

#### Standard WordPress install in subdirectory

* `ABSPATH` === webroot/wordpress
* `wp-config.php` in `dirname( ABSPATH )`
* `site_url()` === example.com/wordpress
* `home_url()` === example.com

`get_home_path()` should return `dirname( ABSPATH )`.

#### WordPress MS install

* `ABSPATH` === webroot
* `wp-config.php` in `ABSPATH`
* `site_url()` & `home_url()` === example.com

`get_home_path()` should return `ABSPATH`.

#### WordPress MS install, wp-config above webroot

* `ABSPATH` === webroot
* `wp-config.php` in `dirname( ABSPATH )`
* `site_url()` & `home_url()` === example.com

`get_home_path()` should return `ABSPATH`.

#### WordPress MS install in subdirectory

* `ABSPATH` === webroot/wordpress
* `wp-config.php` in `dirname( ABSPATH )`
* `site_url()` & `home_url()` === example.com

`get_home_path()` should return `dirname( ABSPATH )`.

**Comment by willmot** [comment]
Currently if `wp-config.php` is above webroot then the plugin will attempt to backup the folder above webroot.

**Comment by mattheu** [comment]
We used to get around this by allowing you to define the hmbkp path. Is this still possible?

**Comment by willmot** [comment]
Yep that's still possible.

`define( 'HMBKP_PATH`, '/path/to/site/root/` );`

**Comment by pdewouters** [comment]
Fixed by https://github.com/humanmade/backupwordpress/pull/788

**Comment by mattheu** [comment]
I'm not sure this is totally fixed by #788. It fixes a bug where a defined path wasn't always used. That allows you to get around the lack of support for WordPress MS install in subdirectory by defining the path. Should you keep this ticket as an indicator that it doesn't work out of the box?

**Comment by willmot** [comment]
Yeah agreed, ideally we'd support all these standard configurations out of the box.

**Comment by willmot** [comment]
This is fixed and unit tested in https://github.com/humanmade/backupwordpress/pull/936
