### ISSUE TITLE
Zip files can't contain files that are larger than 4GB

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#702]
_From @willmot on January 20, 2014 17:15_

We should add a filesize check before attempting to add the file using `ZipArchive` or `PclZip`.

In some situations filesize doesn't work on files over 2GB so would also have to check for `! filesize()`

Needs testing.

_Copied from original issue: humanmade/hm-backup#53_

**Comment by mrdoinel** [comment]
Is there a limit of size for the final Zip ?
I have read that the limit of zip file is 4GB.

My backups of Files will be about 5GB.
Will it fail ? It would generate multiple zips instead ?

**Comment by willmot** [comment]
Not something we run into anymore, was a 32bit limit which is now far less common
