### ISSUE TITLE
Archive DB before files

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#704]
_From @willmot on October 28, 2013 17:36_

In database + files backups the flow looks like this

1. Do a database dump
2. Archive all the files
3. Add the database dump to the archive.

It would be smarter to archive the DB before files.

_Copied from original issue: humanmade/hm-backup#48_

**Comment by pdewouters** [comment]
ha, so I had the same idea - didn't see this ticket

**Comment by willmot** [comment]
Great minds think alike :-)
