### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#711]
_From @willmot on August 24, 2012 16:28_

http://core.trac.wordpress.org/changeset/17592

_Copied from original issue: humanmade/hm-backup#30_

**Comment by willmot** [comment]
Seems like a fairly uncommon but repeated issue

````
PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
````

**Comment by willmot** [comment]
Also saw this alongside it once

````
PCLZIP_ERR_READ_OPEN_FAIL (-2) : Unable to open file \'D:/Inetpub/webs/REDACTED/app_data/_do_not_delete\' in
```

**Comment by pdewouters** [comment]
This happens when there is not enough disk space for the zip operation.

**Comment by willmot** [comment]
Would be obsolete if https://github.com/humanmade/backupwordpress/issues/653 lands
