### ISSUE TITLE
Support tar

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#712]
_From @willmot on May 2, 2012 12:14_

See Total Backup plugin

_Copied from original issue: humanmade/hm-backup#29_

**Comment by willmot** [comment]
A user request for this:

> The possibility to change the compression format from zip to tar etc. Because zip, can't on linux server, unzip greek characters with right names, back.

**Comment by willmot** [comment]
Relies on #717

**Comment by willmot** [comment]
This is made a lot easier by https://github.com/humanmade/backupwordpress/pull/936

**Comment by katmoody** [comment]
So @willmot - do we have any kind of timeline on this? Or it considered secondary to releasing the refactored branch? 

Asking because, per convo with All-Inkl, TAR is the only supported archive functionality for all hosting plans.

**Comment by willmot** [comment]
@katmoody I thought both older versions and the new refactor branch worked on All-Inkl?

No immediate plans to support Tar, we'd probably bring PclZip back first.

**Comment by katmoody** [comment]
They do - but their 'official' stance is that they don't support any archiving methods except for Tar, @willmot

**Comment by willmot** [comment]
I'm not sure what they mean by that but makes me think they don't know what they're talking about. PclZip isn't something a host supports, it's just a php script we ship with the plugin. WordPress uses PclZip to unzip plugins when installing etc.

They also must have ZipArchive otherwise the backups refactor branch wouldn't work as that doesn't have PclZip, only zip and ZipArchive.

**Comment by katmoody** [comment]
I kind of thought as much, but I wasn't going to be the one to educate them ;-)

**Comment by willmot** [comment]
I don't think we should support Tar, or if we do it should be in an extension. I'm going to close this out.
