### ISSUE TITLE
Enable support for 3rd party backup methods

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#717]
There is a lot of duplication
https://scrutinizer-ci.com/g/humanmade/backupwordpress/inspections/6ba9e46c-5c8f-4898-82d0-dc3a2a3c9d19/issues/files/classes/class-backup.php?status=new&selectedLabels%5B0%5D=4&orderField=path&order=asc

**Comment by willmot** [comment]
I'd was thinking we could refactor into several smaller classes.

Something like:

```PHP
abstract class Backup_Model {}

abstract class File extends Backup_Model {}
abstract class Database extends Backup_Model {}

class Zip extends File {}
class Tar extends File {}
class ZipArchive extends File {}
class PclZip extends File {}

class Mysqldump extends Database {}
class Phpmysqldump extends Database {}

```

We could then have the `Backup` class follow a similar pattern to the `Services` class where each implementation of `Backup_Model` registers itself with `Backup`. Something like:

```PHP
class Backup {

    public function register( Backup_Model $backup_model, $priority = 10 ) {
        $this->backup_models[ $priority ] = $backup_model;
    }

    public function run() {
    
        foreach ( $this->backup_models as $backup_model ) {

            if ( $backup_model->run() ) {
                break;
            }

        }

    }

}

```

Thoughts?

**Comment by willmot** [comment]
Implemented in https://github.com/humanmade/backupwordpress/pull/936
