### ISSUE TITLE
Single quote escaping causes import error on SQL dump

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#729]
I found the cause of this.
I have a taxonomy term ending with a single quote ' .
The plugin generated sql file puts a backslash \ before it, but when exported through phpmyadmin it has another single quote before.

Exported by BackUpWordPress:
(421, 'term name\'', 'term-name', 0),

Exported by phpmyadmin:
(421, 'term name''', 'term-name', 0),

**Comment by pdewouters** [comment]
Is this something we control when we do a db dump?

**Comment by owaincuvelier** [comment]
Yeah I saw this on the forum. Wasn't sure as to how much control we did have over the DB dump. cc @willmot

**Comment by willmot** [comment]
We need DB unit tests

**Comment by willmot** [comment]
We have full control over them, that must be the PHP fallback (`mysqldump` won't have these issues)

**Comment by pdewouters** [comment]
Probably here somewhere
https://github.com/humanmade/backupwordpress/blob/master/classes/class-backup.php#L1574

**Comment by willmot** [comment]
This will almost certainly be fixed by https://github.com/humanmade/backupwordpress/pull/835
