### ISSUE TITLE
Throws error with invalid SSL Certificate

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#730]
Should BackUpWordPress have any issues with SSL Certificates being valid or not? I suspect it shouldn't make a difference to BWP.

https://wordpress.org/support/topic/using-ssl-self-signed-certificates-i-get-an-error?replies=1

**Comment by pdewouters** [comment]
I'd try the ALTERNATE_CRON approach

**Comment by willmot** [comment]
Yeah agreed.
