### ISSUE TITLE
Error on activation Version 3.1.3

### ISSUE THREAD

**Issue by mjot** [humanmade/backupwordpress#731]
I receive the following error when trying to install the plugin version 3.1.3:

Parse error: syntax error, unexpected T_STRING in /www/htdocs/blog/wp-content/plugins/backupwordpress/backupwordpress.php on line 34

**Comment by mjot** [comment]
Is this an PHP Version Problem because of "namespace"?

**Comment by mjot** [comment]
Okay, switched to PHP 5.3. Everything fine now!

**Comment by pdewouters** [comment]
:+1:
