### ISSUE TITLE
New files added since last backup are not being added to new backups

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#733]
This was reported by a user via Intercom.
> But to reiterate, the backup only backs up the files that were there when I installed the plug-in, anything after that was added, is not included in the back up. Which is disappointing. Uninstalling and reinstalling resets that and then I'm allowed to back up all the files including the new ones that were added. But then again, if I add files, I'll have to repeat that step.

If bug is confirmed Could this be due to the delta backups? Or is it an issue with the indexing

**Comment by willmot** [comment]
Hmm could be, delta only affects `zip` backups, is he using those?

**Comment by pdewouters** [comment]
I think what's happening is it does the first part of copying the previous archive, but then fails on the second part of updating with new content.

**Comment by willmot** [comment]
Ah that makes sense. Would be good to manually debug and work out why that's happening.

**Comment by willmot** [comment]
This was fixed when we disabled delta backups in https://github.com/humanmade/backupwordpress/pull/773
