### ISSUE TITLE
No need to pass a backup object to action

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#736]
An instance of `Scheduled_Backup` contains a `Backup` object. 
An instance of `Service` contains a `Scheduled_Backup` object.
Therefore you can access the backup object via `$this->schedule->backup

am I missing something @willmot

**Comment by willmot** [comment]
I'm not really sure what you're asking.

We need to pass the current instance of the Backup object to the action in https://github.com/humanmade/backupwordpress/blob/master/classes/class-service.php#L84 so that people hooking in have access to it.
