### ISSUE TITLE
Improve display of Debugging Info used by Intercom for support

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#740]
The way that Intercom displays the data that we collect from the user's WordPress environment is not clearly visible.
I would suggest that we find an alternative.
![screen shot 2015-02-25 at 11 02 44](https://cloud.githubusercontent.com/assets/30460/6369391/ddb2c7cc-bcdd-11e4-813f-20b4a52dbc8f.png)

We could add a "send report by email" or simply display it in a textarea that is easy to copy/paste into the intercom support box. Or can we actually tell the Intercom API to attach it to the message somehow...

**Comment by owaincuvelier** [comment]
This is a recent change, as of a week or so ago. It's quite annoying I agree. I'll send them an email to ask if it's a bug. 



—

**Comment by willmot** [comment]
@owaincuvelier @pdewouters I think the plan was just to stop sending long strings to intercom right? As it places a character limit

**Comment by owaincuvelier** [comment]
That is indeed the plan.

**Comment by pdewouters** [comment]
This has been fixed by Intercom actually.
