### ISSUE TITLE
Fatal error if plugin cant write the status file

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#742]
`Fatal error: Uncaught exception 'RuntimeException' with message 'Error writing to file. (/home/www/web285/html/wp-content/backupwordpress-91bec264e8-backups/.schedule-1424529742-running)' in /home/www/web285/html/wp-content/plugins/backupwordpress/classes/class-schedule.php:851`

We should handle this gracefully

**Comment by willmot** [comment]
I wonder why that would fail...

And what should we do if it does? Try again? Cancel the backup?

**Comment by willmot** [comment]
- Other than silencing the error there isn't really anything we can do here.
- I'd prefer not to silence the error as that's generally bad practice.
- Also this only affects the backup status, the backup itself will continue to run.

Lastly, we haven't seen this error again.

Closing as #wontfix.
