### ISSUE TITLE
Backups stop/hang at 128MB

### ISSUE THREAD

**Issue by paulclarkin** [humanmade/backupwordpress#744]
I run several wordpress sites, hosted on one.com. (Linux (ubuntu i think) & apache)
The BackupWordPress plugin works great for backing up the database, but hangs when I select "files" too. Looking at the zip files created in the backups folder, they always stop at 128MB.

I guess this is a setting on my host. I asked their chat support, but they were useless!

Could you advise on the mechanism used to save the files? Might it suffer from a file size limit imposed by the hosts? Could you change the zip writing to create spanned zips, ideally on a size  specified in the admin?

**Comment by pdewouters** [comment]
@paulclarkin If you haven't done so, may I ask that you submit a ticket through our support system which you can enable from the WordPress dashboard.
Thanks.
