### ISSUE TITLE
Plugin currently blocked by GoDaddy

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#746]
Had a couple of users report this, probably worth reaching out to them to find out why and see what / if we can resolve.

**Comment by owaincuvelier** [comment]
What reports are these?

**Comment by owaincuvelier** [comment]
was it this one? https://app.intercom.io/a/apps/7f1l4qyq/inbox/search/conversations/749965419?q=godaddy

**Comment by willmot** [comment]
Couple of direct emails + it's on their banned plugins list https://support.godaddy.com/help/article/8964/managed-wordpress-blacklisted-plugins?countrysite=ie



Sent while mobile

**Comment by owaincuvelier** [comment]
Cool!

**Comment by pdewouters** [comment]
probably the zip process that can be quite CPU intensive

**Comment by willmot** [comment]
Seems they are potentially doing more than just disallowing it:

> Recently I have been hit with a malware injection virus where it was impossible to get rid of, it kept injecting code continuously, until I moved to a firewall product.
>
>Recently I have discovered that your product backupwordpress is blacklisted by godaddy – they indicated that it was prone to malware attacks. Are there some holes or poorly formed code in this product that needs updating?  I have it on a number of websites and cannot afford this malicious attack again.

That's pretty annoying if it is indeed coming from GoDaddy, I've asked the OP for more details so I can go to GD directly.

**Comment by pdewouters** [comment]
thanks Tom

**Comment by pdewouters** [comment]
What's the status?

**Comment by willmot** [comment]
Sorry still with me, will reach out today 👍

**Comment by willmot** [comment]
Reached out to GoDaddy today, will keep here updated as they respond

**Comment by willmot** [comment]
Maybe https://github.com/fjarrett can help us out here ;-)

**Comment by willmot** [comment]
@owaincuvelier let's add it to here: https://docs.google.com/spreadsheets/d/19hFRF6omWb2GrlkZrQ_dEUqdESu9wMGqbiDc6te9zIM/edit#gid=0

**Comment by owaincuvelier** [comment]
added a note.

**Comment by fjarrett** [comment]
Hey @willmot I'll happily look into this for you.

**Comment by willmot** [comment]
@fjarrett awesome! Happy to take conv elsewhere if sensitive to being public. Thanks for jumping in.

**Comment by pdewouters** [comment]
Seems it's being blocked because it would compete with their own Backup solution

> Backups

> Your Managed WordPress account already provides 30 days' worth of backups, so these plugins duplicate an existing function.

> To backup your site on demand, you can use SFTP access and a database backup plugin like WP-DB-Backup or WP-DBManager.

**Comment by willmot** [comment]
Looks like BackUpWordPress is no longer explicitly mentioned in the list of disallowed plugins, instead as Paul notes above it's likely covered under the Backups catchall statement.

**Comment by fjarrett** [comment]
Hey @willmot and @pdewouters just circling back on this, versions 3.2.1 and higher have been removed from the blacklist.

**Comment by pdewouters** [comment]
thanks @fjarrett

**Comment by willmot** [comment]
Thanks @fjarrett! Any additional feedback available as to why? Was it something we changed in the plugin that caused it to now be acceptable or just an internal change in policy?
