### ISSUE TITLE
Kicking off a directory scan from ziparchive

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#753]
Not sure we should be starting a directory scan at this point as it can potentially take a while.
https://github.com/humanmade/backupwordpress/blob/master/classes/class-backup.php#L1022

**Comment by willmot** [comment]
`get_files` doesn't really "kick off a scan", it's just a directory Iterator.

zipArchive can only add a single file or folder at a time so you have to loop the filesystem and add things individually.

**Comment by pdewouters** [comment]
Shouldn't we ensure that the list is available before running the zip process? if the process has to wait for the iterator to return, could it not timeout?

**Comment by willmot** [comment]
> Shouldn't we ensure that the list is available before running the zip process?

That's not how Iterators work, `RecursiveDirectoryIterator` doesn't create a list of files first and then iterate through them, it loops through the filesystem live. There is no wait

**Comment by pdewouters** [comment]
Here `foreach ( $this->get_files() as $file ) {` 
it calls the `get_files` function which is the iterator function that populates an array which is returned to this foreach loop. This foreach loop has to wait for the iterator function to return the array of files.

**Comment by willmot** [comment]
Iterators don't return the whole array, just the current item, they are a special thing.

Unless I've misunderstood how they work, which is totally possible :-)

**Comment by pdewouters** [comment]
I'd like to chat with you about this next week.

**Comment by willmot** [comment]
👍

**Comment by willmot** [comment]
Would be good to cover this off next week

**Comment by pdewouters** [comment]
This is what I mean: http://recordit.co/8f8orYO2xm
You can see that when it enters the get_files function, there is a `foreach` loop being run on line 1175 which iterates through the filesystem
