### ISSUE TITLE
Function calling loop

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#754]
When instantiating a new Schedule class, here is the sequence of function calls:
Entry point: `__construct()`
calls `set_schedule_start_time()` -> `schedule()` -> `get_schedule_start_time()` -> `set_schedule_start_time()` 

It doesn't seem to cause any issues, but not sure it's ideal

**Comment by willmot** [comment]
I don't see this as an issue. `set_schedule_start_time` is only called in `__construct` if the `HMBKP_SCHEDULE_START_TIME` constant is set. The call to `set_scheduled_start_time` inside `get_scheduled_start_time` is only called if there isn't a start time set, which in this case there is.

**Comment by pdewouters** [comment]
Closing as it is not causing any issues
