### ISSUE TITLE
Performance tweaks to mySql dump

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#756]
Consider using

`--extended-insert, -e`

Use multiple-row INSERT syntax that include several VALUES lists. This results in a smaller dump file and speeds up inserts when the file is reloaded.

**Comment by willmot** [comment]
Another ticket where some solid unit tests for our database backups would help a lot.

**Comment by willmot** [comment]
No longer relevant if https://github.com/humanmade/backupwordpress/pull/835 goes in.
