### ISSUE TITLE
Fallback to other zip method if `-FS` is not supported

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#768]
User reported this error `The message is: (zip error: Invalid command arguments (no such option: S)`
we should test the command and if it returns this error then run it again without this parameter.
maybe pass the options as parameters to the function, would be a similar approach to #530

**Comment by willmot** [comment]
Definitely, I wonder if this is tied to the issue where peoples backups are just getting copied but not uploaded?

**Comment by pdewouters** [comment]
I'm going to add a filter so users can change the options

**Comment by willmot** [comment]
👍 Yeah I think ideally the entire input for the cli commands should be filterable so people can add / change args as they like

**Comment by pdewouters** [comment]
Fixed by https://github.com/humanmade/backupwordpress/pull/773
