### ISSUE TITLE
White screen on backup.

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#771]
Initial testing and some reports indicate that 'run now' just leads to a whitescreen.

**Comment by owaincuvelier** [comment]
todo: investigate

**Comment by owaincuvelier** [comment]
@pdewouters do you think #773 would fix these issues?

**Comment by willmot** [comment]
how did we not catch this :-(

**Comment by owaincuvelier** [comment]
@willmot this is only happening to a small number of sites at the moment.

**Comment by willmot** [comment]
Ah, phew!

**Comment by pdewouters** [comment]
yeah could not reproduce this, could you?

**Comment by owaincuvelier** [comment]
@pdewouters nope. requested/requesting FTP details so we can manually debug

**Comment by owaincuvelier** [comment]
Seems to be fixed.
