### ISSUE TITLE
user_can_connect is missing proper hostname/port/socket check, forces fallback

### ISSUE THREAD

**Issue by MarZab** [humanmade/backupwordpress#774]
https://github.com/humanmade/backupwordpress/blob/6f43a58cac1e024875ee782d83a688aa4ba5578a/classes/class-backup.php#L1854

How to reproduce:
Use custom port on a remote server or a socket.

What happens:
Script goes into mysqldump_fallback, takes forever. :(

**Comment by pdewouters** [comment]
marko

yes this should be fixed in upcoming version
