### ISSUE TITLE
Set correct MIME type for screenshots

### ISSUE THREAD

**Issue by michaelbeil** [humanmade/backupwordpress#781]
When a user clicks on a [screenshot](https://wordpress.org/plugins/backupwordpress/screenshots), the expected behavior is a larger image in a new tab or modal, but instead it's downloaded. Also, the screenshots don't show up in the readme.md, since they're linked to .org. 

![screen shot on 2015-03-28 at 14_25_53](https://cloud.githubusercontent.com/assets/4752949/6882565/1088cc5a-d557-11e4-84a0-ce2ab662a1d0.png)

Referencing https://make.wordpress.org/plugins/2014/03/20/plugin-screenshots-downloading, this can be fixed with the following commands:
`svn propset svn:mime-type image/png screenshot-1.png` 
`svn commit`

**Comment by willmot** [comment]
I commited this on the 3 screenshots but clicking on a screenshot is still triggering a download :-(

**Comment by willmot** [comment]
This is now resolved 👍
