### ISSUE TITLE
Multisite - Can't download.

### ISSUE THREAD

**Issue by mattheu** [humanmade/backupwordpress#787]
When installed on multisite - this is *almost* working.

* The backup is created correctly.
* But the download link doesn't show
* Looks like `get_home_path` doesn't work on Multisiite with WP in a subdir.

Your calculations for the uploads dir are working fine. 

I'm not sure how you can work this out. Perhaps you can avoid using this and get the location of the content dir instead?

**Comment by mattheu** [comment]
Hmm - actually this is pretty important because the this directory is used for the backup root.

**Comment by willmot** [comment]
It's a known issue with multisite when setup with WordPress in a directory

**Comment by willmot** [comment]
As both `site_url` and `home_url` return the root domain instead of `site_url` returning `/wordpress`

**Comment by pdewouters** [comment]
So it's a limitation of WordPress itself?

**Comment by willmot** [comment]
I'm sure there's a way of working it out, it just needs properly digging into, we have a ticket here: https://github.com/humanmade/backupwordpress/issues/695
