### ISSUE TITLE
Support Modal broken

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#793]
JS Error in console. ```Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)```

**Comment by pdewouters** [comment]
Do you have more info on this? I can't reproduce it locally. What error does it cause? Needs more details.

**Comment by owaincuvelier** [comment]
@pdewouters I'm still looking into this, but this error is after you've enabled support.

**Comment by pdewouters** [comment]
Ah yes I see. I'd get in touch with Intercom

**Comment by owaincuvelier** [comment]
I've opened a ticket with them. They're looking into it.

**Comment by owaincuvelier** [comment]
This issue is now resolved. I believe it was something on their end. They stopped replying to my messages :/

**Comment by pdewouters** [comment]
sneaky :D

**Comment by owaincuvelier** [comment]
> may be linked to the Cron array value you are sending for custom data. Theres a limit of 255 characters on custom data attributes and I checked and a few days ago you were sending a value for this that was 1800 characters long but in the more requests this isn't being sent for the user. So I think this is why the request for unprocessable.

Above is the update from them
