### ISSUE TITLE
Travis keeps failing to install WordPress tests

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#807]
`The command "bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION" failed and exited with 1 during .`

**Comment by pdewouters** [comment]
seems like it was a temporary issue

**Comment by pdewouters** [comment]
still happening

**Comment by willmot** [comment]
@pdewouters are you still seeing this happen?

**Comment by pdewouters** [comment]
yes, it happens nearly on every build - one or 2 jobs will fail

**Comment by pdewouters** [comment]
Fixed by https://github.com/humanmade/backupwordpress/pull/889
