### ISSUE TITLE
Backups fail if shell command not executable

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#808]
`WordPress 4.2 - backupwordpress Versión 3.2.4. Error: {"php":{"d48b02d27a9fb68b7aa4cd1f88ec329a":"shell_exec(): Unable to execute 'whoami', \/hsphere\/local\/home2\/aarte103\/elsolnews.com\/wp-content\/plugins\/backupwordpress\/functions\/interface.php, 114"}}`

See http://stackoverflow.com/questions/11471739/shell-exec-error-when-executing-php-script

**Comment by willmot** [comment]
That error has nothing to do with the `php` executable, the error is returned by `shell_exec( 'whoami' );`, nothing to do with PHP

**Comment by pdewouters** [comment]
Yeah I guess that would only apply if the command runs a php script. so probably the user can't run the `whoami` command?

**Comment by willmot** [comment]
yeah, I'm guessing it's that they don't have permission etc. Would go away with #55 anyway so not a huge issue. Although we could at least make sure we are catching the error and not showing the message that uses the output of `whoami` (which we may already be doing).

**Comment by pdewouters** [comment]
https://github.com/humanmade/backupwordpress/pull/833 would fix

**Comment by willmot** [comment]
Going to close as #833 is going in
