### ISSUE TITLE
issues with user database

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#811]
User reported this error message. I logged in an tried to import the database locally but its all pretty corrupt. 

'wfHoover', refers to wordfence. There's so much bloat plugins on the site, I wonder if it's just gotten messed up or something.

![screen shot 2015-04-29 at 15 25 25](https://cloud.githubusercontent.com/assets/1263370/7391827/0f517300-ee84-11e4-8df7-c783cc12ed9d.png)

**Comment by owaincuvelier** [comment]
The BWP error in there is ```mysql_fetch_row() expects parameter 1 to be resource, boolean given, /var/www/vhosts/constructionreviewonline.com/httpdocs/wp-content/plugins/backupwordpress/classes/class-backup.php, 1619, mysql_free_result() expects parameter 1 to be resource, boolean given, /var/www/vhosts/constructionreviewonline.com/httpdocs/wp-content/plugins/backupwordpress/classes/class-backup.php, 1659
```.

**Comment by pdewouters** [comment]
You could try exporting and restoring the database with another plugin or phpmyadmin to see if the same error occurs.

**Comment by owaincuvelier** [comment]
Cool. I got in touch with the user and I'll update here

**Comment by owaincuvelier** [comment]
@pdewouters had another report of this, WordFence again. Still pending the first user's response, going to install WordFence an see what happens.

```
BackUpWordPress Fatal error on vahi.org
mysqldump: Couldn\'t execute \'show create table `wp_wfHits`\': Table \'./cen1201604482762/wp_wfHits\' is marked as crashed and last (automatic?) repair failed (144) 
Undefined variable: rows_cnt, /home/content/52/5919852/html/vahi.org/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1488

Undefined variable: fields_cnt, /home/content/52/5919852/html/vahi.org/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1492

mysql_fetch_row(): supplied argument is not a valid MySQL result resource, /home/content/52/5919852/html/vahi.org/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1512

mysql_free_result(): supplied argument is not a valid MySQL result resource, /home/content/52/5919852/html/vahi.org/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1553HMBKP_SUCCESS
```

**Comment by willmot** [comment]
@owaincuvelier that one looks like https://github.com/humanmade/backupwordpress/issues/707. Basically if one or more of the MySQL Tables is marked as crashed (an internal error in MySQL) then there's we won't be able to back it up. It would be good if we could detect that and show a useful error message though.

Separately it seems our error checking in the mysqldump fallback isn't tight enough. IE we should be checking that we have valid resources before passing variables to `mysql_fetch_row` etc.

**Comment by owaincuvelier** [comment]
@willmot thanks for letting me know. This is interesting. I wasn't aware tables could 'crash'. But yeah, I thought of it as having been corrupt or something along those lines.

Agree'd about a more constructive/functional error message. It sounds simple? I assume we can just check if table's crashed, if so, tell user, 'one of your database tables isn't functioning properly and can't be backed up'. 

Do you know what the possible fixes are? We should present a solution for a problem?

**Comment by willmot** [comment]
So normally when a table is crashed you just need to run a mysql repair on the table / database. in-fact WordPress has the ability to do this baked into core https://codex.wordpress.org/Editing_wp-config.php#Automatic_Database_Optimizing

It's also possible to connect to the database directly and run a repair via CLI or something like Sequel Pro.

We could also try to repair the database as part of BackUpWordPress (maybe just a repair now button in the error message).

**Comment by owaincuvelier** [comment]
> We could also try to repair the database as part of BackUpWordPress (maybe just a repair now button in the error message).

:+1:

**Comment by pdewouters** [comment]
Is the database dump code still up to date? or could we maybe switch to something more recent?
https://github.com/ifsnop/mysqldump-php

**Comment by willmot** [comment]
The database dump code is  the least understood, least tested code in BWP, I'd love to switch to something more modern, with actual unit / integration tests.

**Comment by pdewouters** [comment]
ok, testing that library, it seems relatively popular and has unit tests

**Comment by willmot** [comment]
@owaincuvelier did we ever confirm whether the issue was a crashed table? Did repairing the table resolve the issue?

**Comment by owaincuvelier** [comment]
@willmot yes it resolved the issue IIRC. Left open due to discussion re: building out a repair db functionality.

**Comment by willmot** [comment]
Let's open a new issue for that 👍
