### ISSUE TITLE
Array_key_exists() warning

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#812]
During size calculation this warning can appear, but also can redirect to a 0 I believe. 
Noticed it earlier today, exists in 3.2.5 & 3.2.4.

```
Warning: array_key_exists() [function.array-key-exists]: The first argument should be either a string or an integer in /home/content/06/12072706/html/wp-content/plugins/backupwordpress/classes/class-schedule.php on line 416
```

**Comment by pdewouters** [comment]
Closed in favour of https://github.com/humanmade/backupwordpress/pull/809

**Comment by owaincuvelier** [comment]
:+1:

**Comment by pdewouters** [comment]
Just got a report for this error via Intercom. I wonder if this could be causing it as it returns a number which can be a float `return array_sum( $directory_sizes );`

<img width="1408" alt="screen 20shot 202015-10-21 20at 203 50 14 20pm" src="https://cloud.githubusercontent.com/assets/30460/10662959/cb528818-78af-11e5-8421-fd35075807d0.png">
