### ISSUE TITLE
CONTRIBUTING.md link to http://translate.hmn.md is broken

### ISSUE THREAD

**Issue by michaelbeil** [humanmade/backupwordpress#814]
![screen shot 2015-05-08 at 5 49 26 pm](https://cloud.githubusercontent.com/assets/4752949/7547002/9c292278-f5aa-11e4-9ab5-5dc283d817a1.png)

**Comment by pdewouters** [comment]
thanks, will look into this

**Comment by samwilson** [comment]
This is still happening (or happening again maybe). Now http://translate.hmn.md/ gives `504 Gateway Time-out`.

**Comment by pdewouters** [comment]
@joehoyle would you or someone on the servers team take a look at why this domain is down please?

**Comment by owaincuvelier** [comment]
I'm on it Paul. I haven't had the time this week. 



—
Owain Cuvelier

**Comment by pdewouters** [comment]
what's the status @owaincuvelier

**Comment by owaincuvelier** [comment]
Waiting on Joe to fix some cloudflare thing. I keep reminding him. Will ping again today



—
Owain Cuvelier

**Comment by pdewouters** [comment]
Thanks, we might not need it anymore!
https://make.wordpress.org/polyglots/2015/07/14/translating-themes-and-plugins/

**Comment by owaincuvelier** [comment]
This is fixed at any rate. 

See https://github.com/humanmade/backupwordpress/issues/844 for details on moving forward with translate plans.
