### ISSUE TITLE
to test: expired licence key redirects to "Error page: Error - Options Page Not Found"

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#815]
Todo: test wether entering an expired licence key doesnt behave as expected.

**Comment by pdewouters** [comment]
@owaincuvelier does this happen on the new version? 2.1.0 that's on google drive?

**Comment by owaincuvelier** [comment]
@pdewouters waiting to hear back what version she was using.

**Comment by pdewouters** [comment]
is this on multisite though?

**Comment by pdewouters** [comment]
Fixed + wrong repo
