### ISSUE TITLE
Excludes throws exception: recursive dir iterator.

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#816]
![screen shot 2015-05-12 at 11 51 23](https://cloud.githubusercontent.com/assets/1263370/7585705/612c614e-f89d-11e4-9ddf-17d6dd065ebf.png)

**Comment by willmot** [comment]
@pdewouters I have a vague recollection of you fixing this, am I mad?

**Comment by pdewouters** [comment]
Would be good to see the ticket this came from. We did add some fixes for this type of error, maybe it's a case we hadn't anticipated?

**Comment by willmot** [comment]
Assigning to @owaincuvelier to answer the above

**Comment by owaincuvelier** [comment]
@pdewouters https://app.intercom.io/a/apps/7f1l4qyq/users/54ea340abda51b1c04011211

**Comment by pdewouters** [comment]
No response from users who reported error. Tempted to close as fixed

**Comment by willmot** [comment]
Let's close 👍 can always re-open if it pops up again
