### ISSUE TITLE
No directory listing in excludes

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#817]
Excludes tab doesn't find any files or folders. 

![screen shot 2015-05-12 at 13 34 41](https://cloud.githubusercontent.com/assets/1263370/7587108/ae14c650-f8ab-11e4-85cd-41c8019571ea.png)

**Comment by samwilson** [comment]
It's not strickly a Windows error — I'm using WIndows, and can see the whole directory listing as it should be. Try turning on [debug mode](http://codex.wordpress.org/WP_DEBUG) and seeing if you get any messages.

**Comment by owaincuvelier** [comment]
No I don't think so either. Will take a look into this further.

**Comment by willmot** [comment]
@owaincuvelier did you get anywhere looking into this? My guess, there's a PHP error that's not showing because `WP_DEBUG` is `false`, maybe check the error logs or temporarily enable `WP_DEBUG`?

**Comment by owaincuvelier** [comment]
@willmot I remember the first user to report this resolved it with help from his host.. He told me they'd made changes to his server setup. Only recently had another report of this. Think I was waiting for a response from the user. I'll reach out again an ask for error logs.

**Comment by willmot** [comment]
Great, thanks1

**Comment by owaincuvelier** [comment]
I wasn't able to find the relevant tickets. Too difficult to track down the tickets without manually clicking through 100's of closed tickets. We'll keep this open and jump straight on the next report.

**Comment by willmot** [comment]
@owaincuvelier I say let's close, we can always re-open if / when it re-emerges.

**Comment by owaincuvelier** [comment]
+!
