### ISSUE TITLE
settings on multisite 404

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#818]
```The requested URL /wp-admin/network/admin-post.php was not found```

**Comment by willmot** [comment]
Good catch, looks like the `admin-post.php` path is being calculated incorrectly.

**Comment by pdewouters** [comment]
@owain is this when submitting the license key?

**Comment by owaincuvelier** [comment]
@pdewouters no, when clicking settings or excludes I believe. I'll reproduce the issue between now an Tuesday.

**Comment by pdewouters** [comment]
ah well there was actually a PR https://github.com/humanmade/backupwordpress/pull/813

**Comment by owaincuvelier** [comment]
fixed.
