### ISSUE TITLE
Improve our cron warning message to make it clear that backups won't work

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#821]
Creating an issue for this discussion

**Comment by willmot** [comment]
@owaincuvelier could you flesh this out with the details of the discussion? What's the compat issue?

**Comment by owaincuvelier** [comment]
IIRC, BackDrop uses the HeartBeat API. The HB API uses loopback connections to check its state, (right?). Because BackDrop is used for firing off manual backups, 'run now' does not work on Heart Internet. Schedules fire correctly. But as it stands you can start manual backups. 

@pdewouters that's my current understanding, please correct me if I'm wrong.

**Comment by rmccue** [comment]
Backdrop (assuming the HM one) doesn't use Heartbeat, but it does run a loopback HTTP request similar to WP's cron system.

**Comment by pdewouters** [comment]
Yes, this is related to loopbacks / cron, not the heartbeat API.

**Comment by owaincuvelier** [comment]
Ah ok. Thanks for clearing that up!

**Comment by willmot** [comment]
I think our existing wp-cron message should be enough here then?

**Comment by owaincuvelier** [comment]
So our cron message implies that schedules will not work.. Actually they can work, but it's manual backups that fail. Also, other hosts/server setups that don't allow loopback connections will also suffer from this. We could modify the cron message maybe?

**Comment by willmot** [comment]
> Actually they can work, but it's manual backups that fail.
How can schedules work? schedules rely on wp-cron and wp-cron works by making a loopback request.

> We could modify the cron message maybe?

Agreed, used to be that broken wp-cron just affected schedules, now it affects all backups. @owaincuvelier want to have a bash at updating that message?

**Comment by owaincuvelier** [comment]
>How can schedules work? schedules rely on wp-cron and wp-cron works by making a loopback request.

Yeah you might be right. I thought on HI you could still setup cron tasks through their admin. Mby I'm wrong.

>@owaincuvelier want to have a bash at updating that message?

No problem!

**Comment by willmot** [comment]
Ah got you, yeah that's true you can work around the loopback issue with wp-cron by setting up a real cron to hit wp-cron.php regularly. It is a shame that manual backups no longer work. Maybe we should revisit the reason we switched to BackDrop in the first place?

**Comment by pdewouters** [comment]
because the ajax request timed out and caused false positive errors.
we could possibly not use backdrop but change the ajax request to be non blocking, but poll the server instead at intervals.

**Comment by willmot** [comment]
> we could possibly not use backdrop but change the ajax request to be non blocking, but poll the server instead at intervals.

@pdewouters yeah that's how it worked previously.

**Comment by pdewouters** [comment]
not as I remember. Starting a backup would start an ajax request but it would wait for the backup to finish before returning.

**Comment by willmot** [comment]
It left the request open in order to catch any fatal error output but that wasn't required. There was then a separate polling ajax request which fetched the running status every 5 seconds or so.

**Comment by pdewouters** [comment]
ok, well I agree it's worth exploring. We don't want to shut out users if there is a better way. I'll see if I can find a workaround for catching and reporting fatal errors

**Comment by pdewouters** [comment]
Should we completely remove Backdrop? if it doesn't work for backups then it also won't calculate the filesizes.

**Comment by willmot** [comment]
I still think it's useful for calculating file sizes:

1. It's not a critical piece of functionality.
2. It's not a user initiated action like manual backups are, hence it's more difficult to trigger it with an ajax request.

I'm not wedded to it though, just that it seems like it's mostly working fine for that purpose.

**Comment by pdewouters** [comment]
could we trigger it on plugin activation? user would be redirected to a screen with progress bar.
we could also add a button to 'rescan filesystem'

**Comment by willmot** [comment]
> could we trigger it on plugin activation?

We already do, or do you specifically mean if we switch to running via ajax? On balance I just don't think it's worth it, it mostly works fine as it is using `Backdrop`.

> user would be redirected to a screen with progress bar.

It would be nice to show progress, both in the schedule sentence and the exclude settings. This could come as part of #585, created https://github.com/humanmade/backupwordpress/issues/845 to track that.

> we could also add a button to 'rescan filesystem'

<img width="927" alt="screen shot 2015-07-20 at 18 37 30" src="https://cloud.githubusercontent.com/assets/308507/8783033/3191c46a-2f11-11e5-95f4-ee6d14880256.png">

We already have this, although it could use a title tag to better explain what the botton does (created https://github.com/humanmade/backupwordpress/issues/846). The idea is that you can recalculate any single folder (including root which would then do the whole site), although currently the whole filescan is re-run no matter which folder you click, we have https://github.com/humanmade/backupwordpress/issues/570 to track bringing the ability to just scan a single folder back.

**Comment by pdewouters** [comment]
@willmot @owaincuvelier the discussion here went in different directions from the original title "Improve our cron warning message to make it clear that backups won't work"

This issue is marked for 3.3 release, but I'm not clear on what we want to implement here.

**Comment by willmot** [comment]
The cron error message currently says that scheduled backups won't work, however now that we're using Backdrop manual backups won't work either, we should update the error message to just say all backups won't work.
