### ISSUE TITLE
.htaccess rules block backups, maybe the heartbeat?

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#825]
Would it be possible to send the contents of .htaccess to intercom?

**Comment by owaincuvelier** [comment]
Second user experiencing issues with rules in their htaccess stopping BWP from firing off backups: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/957417127

Will investigate and try an come up with a work around. Allowing 127.0.0.1 did't work!

**Comment by owaincuvelier** [comment]
Any thoughts welcome cc @willmot @pdewouters @joehoyle

**Comment by willmot** [comment]
That .htaccess would definitely break backups (amongst a lot of other things), it's stopping anyone from accessing the site except those coming from the IP listed (probably the site owners home IP).

What that means is that it's going to block the site from visiting itself which is how backups are started and how wp-cron etc. works.

To fix they'll need to work out what IP there site is running at and then allow from that IP also. Alternatively they could allow everyone to access `/wp-cron.php` that way no one can view the site, but when the site tries to visit itself at `/wp-cron.php ` it will be allowed.

**Comment by pdewouters** [comment]
@owaincuvelier could they try this? https://kb.sucuri.net/cloudproxy/Whitelist+and+Blacklist/whitelisting-IP

**Comment by owaincuvelier** [comment]
@pdewouters I don't think that will help. 

The fix for this is to find the IP of your server an add it to the .htaccess.

**Comment by pdewouters** [comment]
but is the htaccess file not generated by the sucuri plugin?

**Comment by owaincuvelier** [comment]
Sucuri is unrelated to this ticket directly, and I know it's the 'deny all' portion of the htaccess block which is preventing the backups. He mentions sucuri but I think it's unrelated to the issue at this point.
