### ISSUE TITLE
Allow control of the schedule ID and resulting filename

### ISSUE THREAD

**Issue by EHLOVader** [humanmade/backupwordpress#826]
I was looking for a way to do this but found myself at a loss. 

Is there a recommended way?
It appears editing the option name does most of it, but could it also break many things?

**Comment by pdewouters** [comment]
There is no way to do this right now, sorry. I would advise against changing the code because it will be overwritten when you update

**Comment by EHLOVader** [comment]
So you are closing this as you don't think it is useful? At least label `wontfix` or something.

I am going to continue with the edited option key name. That is in the database not the code. To avoid issues I could also fork this and maintain a fork. 

Thought of doing that for free S3 remote backups anyway. Could roll my own instead of paying for it.
