### ISSUE TITLE
MySQL views being treated as tables

### ISSUE THREAD

**Issue by samwilson** [humanmade/backupwordpress#827]
With version 3.2.6, I am getting views dumped as tables: the actual view-creation SQL is correct (as in `create view the_view as ...`) but it's preceeded by a `DROP TABLE IF EXISTS the_view` statement, and followed by an attempt to insert data into the view. These statements also can appear *before* the creation of the referenced tables (as it's all alphabetic).

It would be great if views could be treated correctly, and probably moved to the end of the dump file (so that it can be assured that their required tables are already in existance).

Thanks!

**Comment by willmot** [comment]
Definitely sounds like something we should fix, @samwilson do you know how to fix? Would love a Pull Request or a pointer as to how to fix.

Thanks!

**Comment by pdewouters** [comment]
What version of mySQL are you on @samwilson ?

**Comment by samwilson** [comment]
@willmot I'd love to have a crack at it; mightn't find time in the short-term though. :( I'll ask the boss! :)

@pdewouters 5.6 mostly. (I mean, not as in a server is 'slightly 5.5' or anything... ;) Our main servers are at 5.6.)

**Comment by willmot** [comment]
@samwilson Thanks! I'm assuming this is only an issue with the PHP fallback version of mysqldump, could you confirm that (you can see in the server info tab on the help panel in the BackUpWordPress settings screen).

**Comment by willmot** [comment]
Also may be fixed by https://github.com/humanmade/backupwordpress/pull/835

**Comment by willmot** [comment]
@samwilson would you be able to test if this is fixed by https://github.com/humanmade/backupwordpress/pull/835? We're about to switch to a different PHP mysqldump implementation and it may be that this issue is already fixed there.

**Comment by samwilson** [comment]
Yep! That worked percectly it looks like. I was able to restore without issue.

That merge is imminent?

**Comment by pdewouters** [comment]
Thanks for testing @samwilson ! it is pretty close, pending a couple more tests.

**Comment by willmot** [comment]
Closing as #835 is about to be merged
