### ISSUE TITLE
db backup wastes space including data about the backup itself

### ISSUE THREAD

**Issue by ucavus** [humanmade/backupwordpress#829]
Ran a full backup to test the plugin then checked the output. All great except noticed a single, huge record in the db. The source was the transient data `hmbkp_directory_filesizes`. Obviously transients are a convenient, built-in store, but it seems odd to include any info about the backup within it, considering it is not needed before or after the process. On the instance I tested, the (decompressed) extra data was about half a MB, over 10% of the sql.

**Comment by pdewouters** [comment]
Good point. It would be good to skip records with a key of `transient_%` on export.

**Comment by ucavus** [comment]
Even better. Also, they start with `_transient_`.

**Comment by ucavus** [comment]
Wait, is that bad for other transients with a distant expiry?

**Comment by owaincuvelier** [comment]
I expect so. We don't know what random uses developers could be using transients for. To minimise potential damaging side effects, I would lean toward the side of; only excluding our own transients, and leaving all others.

**Comment by pdewouters** [comment]
yeah, I was unclear there, I meant any transient with `hmbkp_` prefix

**Comment by willmot** [comment]
I think it would be fine to just not backup all transients (although not sure whether that's performant or even possible with native `mysqldump`). Transients are a cache and it doesn't make sense to backup cached data.

**Comment by willmot** [comment]
Happy to take a PR for this, I've added to the Future Release milestone to indicate it's an approved backlog item

**Comment by willmot** [comment]
We could also store this data in a file rather than in the DB https://github.com/humanmade/backupwordpress/issues/585

**Comment by willmot** [comment]
In #1008 we switched to storing this data in a hidden file.
