### ISSUE TITLE
Create dev blog for BackUpWordPress

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#843]
Can we have a subdomain of `hmn.md` to host our dev chat blog?
@owaincuvelier would you mind setting it up please?

**Comment by owaincuvelier** [comment]
@pdewouters I can do that. Do you know what domain we want?

**Comment by willmot** [comment]
let's go with `https://dev.bwp.hmn.md`

**Comment by owaincuvelier** [comment]
https://dev.bwp.hmn.md/ need to fix ssl issue. Will close ticket when that's done.

**Comment by owaincuvelier** [comment]
So we can have dev.bwp.hmn.md without SSL issues. So I've switched it to https://dev-bwp.hmn.md/

You happy with this? @willmot @pdewouters

**Comment by pdewouters** [comment]
great, thanks
