### ISSUE TITLE
Plan for moving translations to WordPress.org

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#844]
Once plugin translations on WordPress.org are live, we can move our translations over.
https://make.wordpress.org/polyglots/2015/07/14/translating-themes-and-plugins/

Readme translation is also supported.

**Comment by willmot** [comment]
\0/

**Comment by pdewouters** [comment]
This is happening soon:

````
Next week, we intend to import the plugin listed above into the translate.wordpress.org translation system. Language packs will also be enabled for your plugin, for any locales that are fully translated (at 100%).

As part of this process, all of the strings in your plugin will be imported into translate.wordpress.org. Additionally, any language files that you ship with your plugin ("mo" files) will be imported and synced with their respective locales within translate.wordpress.org.

For your plugin to be imported properly, it needs to have a text domain that matches your plugin slug: backupwordpress.

Keep in mind that the text domain must be added as an argument to each gettext call and you cannot use a variable or constant in its place. Additionally, multiple text domains are unsupported by the translation system. If you use a framework for you plugin, its strings will not be imported. We recommend you change the gettext calls in the framework to use your text domain.

More information on how to properly internationalize plugins is available in the plugin developer handbook:

https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

Finally, you can visit this link for more information about the overall import process:

https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/

````

**Comment by willmot** [comment]
Looks like BackUpWordPress has already been imported https://translate.wordpress.org/projects/wp-plugins/backupwordpress/dev/af/default

@pdewouters do you have a handle on what we need to do to switch to this system?

**Comment by pdewouters** [comment]
@willmot awesome, so we need to get all translators on board so that they translate the strings directly on `translate.wordpress.org` instead of our `translate.hmn.md`

Also, once a language reaches 100%, we can remove the po/mo files from the plugin download
https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/#comment-42255

**Comment by willmot** [comment]
Great!

**Comment by willmot** [comment]
I guess we should also update docs, readme etc to point to translate.wordpress.org instead of translate.hm.md.

**Comment by willmot** [comment]
@pdewouters I think we're now good here?

**Comment by pdewouters** [comment]
yes
