### ISSUE TITLE
Switch to running scrutinzer on PR

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#852]
We're currrently running Scrutinizer on both PR's and branch pushes, do we really need the latter? Can we just switch to PR's tracking? Seems like it would avoid a lot of wasted inspections.

**Comment by pdewouters** [comment]
Yes, good idea

**Comment by willmot** [comment]
Oh, I tried disabling it and it error'd saying you have to have Push tracking enabled if you want PR tracking.
