### ISSUE TITLE
Make it easier to join the public Slack channel

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#857]
I found this handy plugin: http://wptavern.com/new-wordpress-plugin-automates-slack-team-invitations, we should add it to bwp.hmn.md

**Comment by pdewouters** [comment]
also https://github.com/rauchg/slackin

**Comment by pdewouters** [comment]
Another solution discussed on slack is to whitelist the WP.org accounts

**Comment by willmot** [comment]
We're no longer using the public Slack so let's close
