### ISSUE TITLE
Inconsistent help text style on settings

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#859]
<img width="919" alt="screen shot 2015-07-20 at 18 36 35" src="https://cloud.githubusercontent.com/assets/308507/9060402/51480468-3aab-11e5-9121-dbc0794ca530.png">

**Comment by pdewouters** [comment]
I meant for it to stand out

**Comment by willmot** [comment]
I think being consistent is more important, reverted in 0abea48
