### ISSUE TITLE
Remove composer.phar from plugin

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#861]
Composer.phar shouldn't be in the public release of BackUpWordPress, let's remove it.

**Comment by pdewouters** [comment]
@owaincuvelier is it in BWP or one of the addons?

**Comment by owaincuvelier** [comment]
@pdewouters in BackUpWordPress. Root dir according to this:
![2015-07-27_18-24-11](https://cloud.githubusercontent.com/assets/1263370/9731870/9d81db88-5617-11e5-9277-379d2d1008c7.png)

**Comment by pdewouters** [comment]
well that's weird. because it's not included in the plugin. is there an intercom ticket?

**Comment by owaincuvelier** [comment]
https://app.intercom.io/a/apps/7f1l4qyq/inbox/search/conversations/1044245428?q=composer

I think there's 1 or 2 others but cant find it off the keyword alone.

**Comment by pdewouters** [comment]
Ah, for some reason it is included! http://plugins.svn.wordpress.org/backupwordpress/tags/3.2.7/
