### ISSUE TITLE
[Question] Possibility for encryption?

### ISSUE THREAD

**Issue by vincentcox** [humanmade/backupwordpress#870]
Hi there,

Is there a possibility for encrypted backups?
You may ask why:
-> If a hacker gets a webshell on your wordpress site, he/she can easily download a backup and have all the content.
Or is the encryption too cpu intensive and it's not worth it because a webshell means that your whole site is owned anyway?

**Comment by owaincuvelier** [comment]
>it's not worth it because a webshell means that your whole site is owned anyway?

Basically yeah!
