### ISSUE TITLE
Automate adding new changelog to new release readme file

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#896]
Steps:
- generate changelog from git log.
- append current readme footer text file to end
- replace existing readme footer text file.

**Comment by willmot** [comment]
I'm not convinced that the git log makes a good changelog, it often includes a bunch of very small things that don't warrant inclusion and can leave changes which warrant explanation hidden behind poorly written commit messages.

Maybe we can just improve our commit messages to solve this but I wonder whether changelogs are just better off being written by a Human. What do you think?

**Comment by pdewouters** [comment]
There is certainly room for improving commit messages, it's true that the current changelogs haven't been great.
I do usually edit the change log manually anyway, so I could take more time to make it more meaningful/helpful rather than a list of commits.

**Comment by willmot** [comment]
Ah cool, if there's still a manual step at the end then I think auto pulling in the `git log` output as a starting point is really useful

**Comment by pdewouters** [comment]
I was doing something similar to https://johnblackbourn.com/git-changelog-generator
