### ISSUE TITLE
Godaddy Permissions

### ISSUE THREAD

**Issue by meeware** [humanmade/backupwordpress#902]
We've known for a while that GoDaddy do not permit backup plugins - and yet backupwordpress is ranking in their top 100 plugins! https://garage.godaddy.com/wordpress-hot-100/

There is a page that explains which plugins are not permitted on godaddy - it's an explicit blacklist, and we're not on it, though one of the reasons for blacklisting is 'being a backup plugin'. https://uk.godaddy.com/help/blacklisted-plugins-8964

So, I asked what thew deal was:
> Hi,
This is a question I ask with sliiiiight trepidation - so one of our plugins is in the top100, which is really great to see. BUT, it's a backup plugin. We were under the impression you didn't allow backup plugins (and the blacklist page on your site says some such plugins are banned because they're redundant). 
So what's the line? is our plugin OK? Or I have asked, alerted you, and just triggered a process that's gonna get us blacklisted (knew I shoulda kept schtum!).
Ant

, and got this response:
> Hey Ant, good question.  Human Made’s current version of the backup plugin is NOT blacklisted anymore. You’re currently good to go.  :-)
For a bit of context, backup plugins are the most problematic for our customers, e.g. filling up a user’s disk space quota due to poor default settings or poor code quality.
That said, not all backup plugins are bad.  But as you can imagine, with tens of thousands of plugins and millions of customers it’s difficult to investigate each individual plugin issue our customers have.  Instead we try to identify trends, which aren’t perfect.  We’re getting better at investigating these issues and developing relationships with plugin makers, so thanks for being part of the process.
Just last weekend I completed a review of our blacklist and removed yours.  We must still maintain a version of the plugin on the blacklist for tracking purposes, so we’re only blocking 3.2.0 and lower.
As an aside, lately we’ve been having more issues with backup plugins across all of our hosting environments.  We’ve discussed the issue with other hosts (some have decided to block backup plugins completely), but we’ll have an internal discussion on how to address the issue next week.  Broadly I believe backup plugin authors can do a better job of adding smart defaults in plugins, encouraging off-site backups, and implementing safeguards to prevent novice users from filling up their disk space quota with unnecessary backups.  I’m interested on your thoughts on the issue.
Thanks,
Gabe

So, here's the thing - there is a discussion we can be a part of, and possibly look to join with other hosts. I can imagine a shared 'whitelist' of well bahaved backup plugins too actually.

**Comment by willmot** [comment]
So there's a few worthwhile enhancements we can pull out of this:

- smart defaults
- encouraging offsite backups
- disk space safeguards

I'm going to open a bunch of enhancement issues related to those 3 things:

**Smart Defaults**

We can have the plugin make smart choices for the user based on the things we know about their site

- Exclude suggestions - https://github.com/humanmade/backupwordpress/issues/905
- Auto exclude some files / folders - https://github.com/humanmade/backupwordpress/issues/906
- Reduce number of stored backups if disk space is low - https://github.com/humanmade/backupwordpress/issues/907
- Auto backup before an update is performed (Core, Plugin, Theme) - https://github.com/humanmade/backupwordpress/issues/39

**Encouraging Offsite Backups**

It's highly important that users of our plugin store their backups offsite. For the following reasons (among others):

- You don't lose your backups if your site is wiped
- Backups don't take up your web space
- More secure as backups aren't stored in a web accessible location
- Makes it easy to share, download or sync the backups elsewhere as you can make use of your cloud providors tools

We could and should do more to encourage people to store their backups offsite. There are multiple angles to this, we'll use this as a master issue for discussion with specific implementation details split off into other tickets.

- Make the FTP extension free - that way users have a free offsite backup option - https://github.com/humanmade/backupwordpress/issues/903
- A setup wizard which walks the user through setting up an offsite backup - https://github.com/humanmade/backupwordpress/issues/904
- Seamless installation of the offsite backup extensions - https://github.com/humanmade/backupwordpress/issues/525
- Some kind of note / warning on backup schedules that aren't being sent offsite.
- A clear indicator of where offsite backups are being stored - https://github.com/humanmade/backupwordpress/issues/805
- Support not storing any local backups - https://github.com/humanmade/backupwordpress/issues/858

**Disk Space Safeguards**

At the moment BackUpWordPress will continue to perform backups even if disk space is low and doing so would cause it to fill up. This is stupid and wrong. We should do our best to work out whether the user is low on disk space and warn them / take action

- Warn users who are low on disk space - https://github.com/humanmade/backupwordpress/issues/615
- Reduce the number of stored backups if disk space is low - Reduce number of stored backups if disk space is low

**Comment by meeware** [comment]
I think I'll write back and thank them for the really valuable feedback. Might there be value in giving them visibility of the issues we're picking off?

**Comment by willmot** [comment]
Yep I'd drop them a link to this github issue (it's public) and also cc in Paul (as BWP lead dev), Owain (as support lead) and myself.

**Comment by meeware** [comment]
cool, thansk

**Comment by fjarrett** [comment]
Thanks @willmot and @meeware! I'll subscribe to this thread.

**Comment by willmot** [comment]
Great thanks @fjarrett. One thing I'd love your take on actually.

We'd love to do a better job of detecting disk usage and either intelligently adjusting settings or at least letting users know that they're near and should do something about it. We tried this before but `disk_free_space` ends up being pretty innacurate as the amount of physical disk space is often not the same as a users disk quota and those disk quotas seem to be enforced in propriatary ways which PHP doesn't have access to. Do you know if there's a sane way we can detect a users remaining free space on GoDaddy (I'd also guess the answer might be different depending on which GoDaddy hosting product the site is on).

**Comment by fjarrett** [comment]
Hey @willmot I'll email you.

**Comment by willmot** [comment]
Thanks!

**Comment by willmot** [comment]
Closing this one out as we've got individual tickets for various enhancements planned
