### ISSUE TITLE
Potential issue with browsing excludes on windows

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#934]
https://wordpress.org/support/topic/cannot-browse-files-to-exclude?replies=1#post-7613051

**Comment by willmot** [comment]
This is fixed in #936.

@katmoody going to leave this issue open, we can ask them to beta test the next release to see if it resolves their issue.

**Comment by willmot** [comment]
@katmoody could you reach out to the folks in that thread to see if 3.4 RC1 fixes their issue?

**Comment by katmoody** [comment]
Have left a message and will report back with results.

**Comment by willmot** [comment]
Making as closed as I verified this locally. We can re-open if that guy comes back with it still being an issue.
