### ISSUE TITLE
Add in Ability to Rename Backup Schedules

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#947]
When setting up new backup schedules, especially with sites who utilize a split schedule to complete their full site backup, having a unique name for each schedule would be better than the default names assigned, which tend to get confusing if you add multiple schedules.

**Comment by willmot** [comment]
Definitely something we want to support, we have an existing ticket actually https://github.com/humanmade/backupwordpress/issues/351 so I'll close this one to avoid duplication.
