### ISSUE TITLE
Consider applying to the GoDaddy WordPress Plugin Partner Program

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#949]
The partner program is new and in beta, so early adopters would have much to gain. Joining would allow us to have more help troubleshooting specifically for GoDaddy hosting environments, which are sometimes problematic. 

Application link: https://garage.godaddy.com/wordpress-plugin-partner-program/
We meet the criteria: 
* 5K active installs on GoDaddy
* No major outstanding platform compatibility issues (this is the only potential issue since shared hosts limit the server resources - but they might help resolve this?)
* Not blacklisted
* No hooks or affiliate links to other hosting companies
Intro post: https://garage.godaddy.com/webpro/wordpress/introducing-the-godaddy-plugin-partner-program-for-wordpress/

**Comment by katmoody** [comment]
ps - not sure which label to put this under? @owaincuvelier ?

**Comment by pdewouters** [comment]
Relevant feedback and action points regarding Godaddy: https://github.com/humanmade/backupwordpress/issues/902#issuecomment-145493174

**Comment by willmot** [comment]
We're in!

@katmoody could you open a new issue to cover off what we need to do (if anything) now that we're in. Thanks!
