### ISSUE TITLE
Monthly Google Drive destination folders 

### ISSUE THREAD

**Issue by laptopleon** [humanmade/backupwordpress#957]
If a backup destination folder is set from the Google Drive window, 'myWebsiteBackup' for example, it will be ignored (probably unavailable for backup somehow) after one month.

Instead, a new folder is created with a similar name, but with a '(1)' added, i.e. 'myWebsiteBackup (1)'.

**Comment by willmot** [comment]
We need to move this to the https://github.com/humanmade/backupwordpress-pro-gdrive repo

**Comment by laptopleon** [comment]
Maybe it's interesting to know that new 'folders of the month' seem not to be created on the first backup occasion in a new month, but a month from the initial backup.

For example, a backup rule that was created and first run on December eighth, creating a backup to a gDrive folder named myWebsiteBackup on that day, seems to work fine until Januari eighth. Then, a new folder myWebsiteBackup(1) is created to store net backups.

Another month later, on the eighth of February, a new folder myWebsiteBackup(2) appears, etc.

**Comment by katmoody** [comment]
Closing this issue - all additional notes can go on issue on the Pro-drive extension's repository here: 
https://github.com/humanmade/backupwordpress-pro-gdrive/issues/41
