### ISSUE TITLE
Calculated backup size is far to high

### ISSUE THREAD

**Issue by laptopleon** [humanmade/backupwordpress#958]
When opening a BUWP schedule, the size of the backup is automatically calculated and after some time displayed. This calculation is consequently far to high. A typical situation looks like this:

![calculation](https://cloud.githubusercontent.com/assets/6651573/12169810/ba328aa6-b53b-11e5-8b3a-abcb385090d9.jpg)

In this exemple, the calculated size is 357 MB, while in reality it is 80 MB, less then a quarter. No excludes were set. This happens on all different sites and servers I use.

**Comment by willmot** [comment]
This is likely correct, typically the database will compress about 10 - 20x, so if you have a 250MB DB it'll compress to 10 - 20MB range.

Best bet, download one of the backups and unzip it, uncompressed it should then match the calculated size.

**Comment by willmot** [comment]
Feel free to re-open if that's not the case.

**Comment by laptopleon** [comment]
For a second, I thought you were joking   :·)   You have a point, that the uncompressed files are larger, but still, in this case, they are 120.946.557 bytes. On my Mac they take up 129,6 MB (because of partially unused block etc) so on the server it might be slightly different, but 357 MB is still way off. I'll therefore re-open it. If I'm missing something, please say so. DB's compress very well but .jpgs don't. Most sites, specially the larger data sets, have a lot more .jpg data on them than DB/text.

Another thing is the user experience. Quite a few users will expect the calculated number to have the same scope as the numbers in the list right below it, because it is all in the same backup context / backup plugin page. Therefore, may I suggest to mention in the message that the calculated size is about the uncompressed files? It would even be more user friendly, to also put an estimated zipped size behind it.

Something like…
Backup my database and files (130 MB, before ZIP-ing, about 80 MB ZIPped) manually, store the last 3 backups in blog/wp-content/uploads/backupwordpress-whooptidoo1234567ad-backups. Send an email ...etc.

**Comment by willmot** [comment]
Ah that sure doesn't sound right then, are you able to browse your site using the excludes interface to see where that additional space is coming from?

**Comment by laptopleon** [comment]
You mean to find a clue as to why the calculated size adds up to 357? According to the excludes interface, the /home dir is 111 MB, so that doesn't explain it. What comes to mind are the three backup zips, each about 80 MB, would be about 240 MB. With the 111 MB of the home dir, it's 351, quite close to the 357 that the calculation comes up with  ;)   Makes you thing that the old BUWP zips might be added to the count as well, while they are (and should) not included in the actual backup.

**Comment by willmot** [comment]
> You mean to find a clue as to why the calculated size adds up to 357?

Yep exactly

>  Makes you think that the old BUWP zips might be added to the count as well, while they are (and should) not be included in the actual backup.

That could be the case, any way you can test that theory (say by deleting one and forcing a recalculation).

**Comment by laptopleon** [comment]
Interestingly, now the calculated number is almost spot-on: 117 MB while it is 111 according to the excludes page. This is even before I dumped a backup or anything. Can it be that by clicking the excludes link, something is triggered, so that the calculation is corrected?

It stayed 117 after dumping a backup and after adding the new one.

**Comment by willmot** [comment]
The site size is calculated and then cached for a week, so more likely that was just an old cached value and your site has since reduced in size?

**Comment by laptopleon** [comment]
This site has hardly changed a bit for a year, not even the number of backups in the backup folder has changed. Just the usual WP / plugin updates. Can't think of anything that explains the 357-117 difference.

Also, I've had this with many other other sites. For example:
![artbeat](https://cloud.githubusercontent.com/assets/6651573/12174688/7d8cb4b4-b55e-11e5-9536-e6c07ff3d712.jpg)

**Comment by laptopleon** [comment]
Again, this second example now displays a more realistic calculation(!) after just clicking to the main plugin page and back.. Both sites have been updated to the latest version of WP today.

**Comment by willmot** [comment]
hmm ok, can't be that then. I'm running out of ideas without doing a bunch of digging, willing to accept this does seem like a bug though. Thanks for helping investigate 👍

**Comment by willmot** [comment]
@laptopleon there's a bunch of improvements to how the site size is handled in #1008 & #1010, if your able I'd appreciate it if you could test them out and see if they improve the accuracy of the sizes you're seeing.

I've ran through a bunch more testing whilst implementing both of those PR's and the sizes were accurate. Going to close this out but do re-open if you do re-test and still have issues.
