### ISSUE TITLE
ERROR on Update to 3.4: open_basedir restriction in effect

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#964]
From Intercom Ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1765944325

```
Warning: file_exists(): open_basedir restriction in effect. File(/home/.sites/124/site9073757/wp-config.php) is not within the allowed path(s): (/home/.sites/124/site9073757/web:/home/.sites/124/site9073757/tmp:/usr/share/pear) in /home/.sites/124/site9073757/web/wp-content/plugins/backupwordpress/classes/class-path.php on line 107 Warning: file_exists(): open_basedir restriction in effect. File(/home/.sites/124/site9073757/wp-config.php) is not within the allowed path(s): (/home/.sites/124/site9073757/web:/home/.sites/124/site9073757/tmp:/usr/share/pear) in /home/.sites/124/site9073757/web/wp-content/plugins/backupwordpress/classes/class-path.php on line 112 1 
Warning: file_exists(): open_basedir restriction in effect. File(/home/.sites/124/site9073757/wp-config.php) is not within the allowed path(s): (/home/.sites/124/site9073757/web:/home/.sites/124/site9073757/tmp:/usr/share/pear) in /home/.sites/124/site9073757/web/wp-content/plugins/backupwordpress/classes/class-path.php on line 107 Warning: file_exists(): open_basedir restriction in effect. File(/home/.sites/124/site9073757/wp-config.php) is not within the allowed path(s): (/home/.sites/124/site9073757/web:/home/.sites/124/site9073757/tmp:/usr/share/pear) in /home/.sites/124/site9073757/web/wp-content/plugins/backupwordpress/classes/class-path.php on line 112```

**Comment by pdewouters** [comment]
We had a fix for this, not sure why it doesn't work in this case
https://github.com/humanmade/backupwordpress/blob/11eccaefbdcecc2f400088c344eb38c084efc089/functions/interface.php#L393

**Comment by willmot** [comment]
`is_restricted_custom_path` just tests whether the path itself is restricted, however in [`Path`](https://github.com/humanmade/backupwordpress/blob/master/classes/class-path.php#L107) we now do `file_exists( dirname( $site_path ) . '/wp-config.php' )` to check for the existence of a `wp-config.php` file outside of webroot. That check was added in #936 as a fix for https://github.com/humanmade/backupwordpress/issues/695.

So we could either extend `is_restricted_custom_path` to cover testing the directory up from site root as well or add a new function for that.
