### ISSUE TITLE
Avoid showing users useless backup errors

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#970]
**Feel free to edit this - I wasn't positive how to categorize it. 

Basically, mysqldump, sh and mysql are all coming up with an error saying they can't be found? 

![screen 20shot 202016-01-23 20at 2021 59 53](https://cloud.githubusercontent.com/assets/5481211/12533686/44bc3da8-c206-11e5-89e4-16b65a32a331.png)

The Intercom ticket is here: https://app.intercom.io/a/apps/7f1l4qyq/inbox/katrina@katsmedia.com/conversations/1767900867

**Comment by katmoody** [comment]
And another ticket now ... I'll add them all under this one if additional tickets involved show up, okay? 

https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1783509143

**Comment by willmot** [comment]
👍

**Comment by pdewouters** [comment]
By looking at the screenshots, seems backup are running anyway?

**Comment by willmot** [comment]
Just to note, those errors don't mean that the backup didn't work, just that there were errors in the `mysqldump` command and so the plugin had to fallback to the PHP fallback.

We need to do a better job of only showing relevant errors to users. At the moment users get confused because they see errors like that and think it means their backup didn't work, which isn't true.

**Comment by katmoody** [comment]
Just a note - those are showing despite MySQLDump being installed on the server - it just can't find those commands? With so many seeing that warning, does that mean anything else could be going on aside from it being an ignorable error?

**Comment by pdewouters** [comment]
This is tied to a nexisting issue about showing useful error messages, as we need a smart way to filter what is useful to show to the user. Or can we change the wording as we had before?

> Last backup was successful, generated some warnings that are probably safe to ignore.

**Comment by willmot** [comment]
Couple of points:

- We shouldn't show errors from backup methods that weren't actually used. For example if the plugin tries `zip`, fails and then fallback to `ziparchive` we should just suppress the warnings from `zip`.
- For warnings that do show we should start a whitelist to ignore the ones we no don't actually impact the creation of the backup file.
