### ISSUE TITLE
Trying to download backups leading to 404 Error

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#975]
Multiple users reporting they are unable to click to download the file from their admin. I was able to work on the first site and noted that the download URL doesn't seem to be passed correctly? 

```
http://mefemn.org/site/wp-admin/admin-post.php?hmbkp_backup_archive=L2hlcm1lcy9ib3NvcmF3ZWIwNTMvYjE4NzcvaXB3Lm1lZmVtbm9yZy9wdWJsaWNfaHRtbC9zaXRlL3dwLWNvbnRlbnQvYmFja3Vwd29yZHByZXNzLTM3ZDI4NWRhNTYtYmFja3Vwcy9tZWZlbW4tb3JnLTE0NDAwMTQ5MTItY29tcGxldGUtMjAxNi0wMS0yNi0xNC0wMi0xNy56aXA%3D&hmbkp_schedule_id=1440014912&action=hmbkp_request_download_backup&hmbkp_download_backup_nonce=fa2c67ad27
```

That's what I get if I try and copy the download link so I can just open it in a new window - and it will come back to a 404 error. 
This ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1774343266

**Comment by katmoody** [comment]
Here's another, but the guy isn't very technical - https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/1784702189

**Comment by katmoody** [comment]
From the forums: 
https://wordpress.org/support/topic/link-to-download-backup-gets-404-err-site-subdir-not-in-link?replies=2#post-7944669
and
https://wordpress.org/support/topic/download-link-is-missing-wp-address-urls-sub-folder-in-link-gets-404-not-found?replies=3#post-7944684

**Comment by pdewouters** [comment]
Ok, so this condition does not take into account when `wp-config.php` is in the subdirectory, which is valid for a subdir install

```
			if ( file_exists( dirname( $site_path ) . '/wp-config.php' ) && ! file_exists( $site_path . '/wp-config.php' ) && file_exists( dirname( $site_path ) . '/index.php' ) ) {
				$home_path = dirname( $site_path );
			}```
https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory

<img width="270" alt="screenshot 2016-01-27 15 54 45" src="https://cloud.githubusercontent.com/assets/30460/12619048/4c45b558-c50e-11e5-8ebe-37ee25b38c4b.png">
