### ISSUE TITLE
Master version triggers 500

### ISSUE THREAD

**Issue by TweetPressFr** [humanmade/backupwordpress#980]
Hi,

Do you know master is currently unstable and triggers 500 unlike wordpress.org version ? #

**Comment by pdewouters** [comment]
Did you clone the repo? You need to run `composer install`

**Comment by TweetPressFr** [comment]
of course ;)

**Comment by pdewouters** [comment]
@TweetPressFr do you have more info than the 500 error? can  you check the PHP error log?
