### ISSUE TITLE
Plugin Update error

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#982]
Error accompanied by 503 service unavailable error on trying to update.
```
object from empty value in /home/travellerrest867/public_html/wp-content/plugins/backupwordpress-pro-dropbox/vendor/humanmade/bwp-common/PluginUpdater.php on line 85
```

Will update ticket with further issues once they've gotten back with me.

**Comment by pdewouters** [comment]
Should this be on the Dropbox repo?

**Comment by katmoody** [comment]
I originally left it here because it is happening with more than one plugin - once I get some confirmation I will update and move as accordingly, okay?

**Comment by willmot** [comment]
Any further update here @katmoody?

**Comment by katmoody** [comment]
No one has come back to me on this one. Let's close until they do so? Maybe it was a glitch?

**Comment by willmot** [comment]
Yeah let's close 👍
