### ISSUE TITLE
Unable to exclude core WP folders when inside subdirectory

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#984]
This is a weird one. 

User's site is actually located in a subdirectory from root - but another site is installed on root . When we go to try and exclude files - when we try to exclude the root's wp-admin or core folders, they also exclude the same folders in his subdirectory site.

https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1847513108

**Comment by katmoody** [comment]
The beta version does seem to fix this issue for, so far, 100% of respondents :D

**Comment by willmot** [comment]
@katmoody if this is fixed by #976 then I think it's safe to close this issue.
