### ISSUE TITLE
Fatal Error upon update check - tied to 'Force Plugin Updates' plugin

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#985]
This isn't a fatal error in that the wp-admin, but it doesn't bring the whole its down. It happens specifically when I click on the "Check for Updates" in the wp-admin bar across the top of the screen. 

```
Fatal error: Class 'HM\BackUpWordPress\stdClass' not found in /home/katsmed1/public_html/bwp/wp-content/plugins/backupwordpress-pro-gdrive/vendor/humanmade/bwp-common/PluginUpdater.php on line 75
```

![index php](https://cloud.githubusercontent.com/assets/5481211/12850904/2ce8b186-cbf5-11e5-9fbd-60bb195eee19.jpg)

**Comment by katmoody** [comment]
Upon further checking I think it is tied directly to the "Force Plugin Updates" plugin, which gives that dropdown to check for plugin updates on the top menu. When I deactivate that plugin, I can't get to that dropdown menu and I don't get that error when I simply try to update.

**Comment by pdewouters** [comment]
@katmoody that's the issue I thought I had fixed yesterday

**Comment by katmoody** [comment]
Just happened for me today?

**Comment by pdewouters** [comment]
It will happen on versions which don't have the fix, yes. The error only seems to be apparent with the Force Update plugin though. 
Closing as fixed in newer versions
