### ISSUE TITLE
Make Plugin work with FreeBSD OS

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#987]
This OS platform has been coming up a few times in support and it doesn't look like there would be a lot of effort to make it work. It also worked prior to the WP 4.2.2 update, signifying that something changed there that we can potentially change back. 

Here's a ticket on Intercom - https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1810118208

**Comment by pdewouters** [comment]
less than 1% of users on intercom
<img width="232" alt="screenshot 2016-02-05 16 44 48" src="https://cloud.githubusercontent.com/assets/30460/12852656/f924f278-cc27-11e5-93dd-72d0863d3ba8.png">

**Comment by willmot** [comment]
I actually don't think the OS will have anything to do with this. Will look into it though.

**Comment by willmot** [comment]
I'm going to close this as there's no indication to me that the OS would be at fault here. I've got the original support request assigned to me so will open a new issue if I find something.
