### ISSUE TITLE
Support space-delimited when checking for disabled functions

### ISSUE THREAD

**Issue by willmot** [humanmade/backupwordpress#994]
The PHP docs only mention comma-delimited, but local testing and https://wordpress.org/support/topic/warning-exec-has-been-disabled-for-security-reasons-1?replies=7 show that space-delimited also seems to work.

**Comment by pdewouters** [comment]
Just my opinion, but I think we should just support the syntax that is in the PHP docs. I think I remember seeing an example that used `:` as the separator. 

Could you confirm that it actually disabled all functions in a space delimited string? Even if `exec` isn't the first entry?

**Comment by willmot** [comment]
If it causes the function to be disabled we need to support it, otherwise we'll try to use the function and fail.

**Comment by willmot** [comment]
Just confirmed it still disables if exec isn't the first entry

**Comment by willmot** [comment]
I just tested `:` and it does't disable the function

**Comment by pdewouters** [comment]
ok, cool. so spaces or comma then.
