### ISSUE TITLE
Unable to fork [echo backupwordpress]

### ISSUE THREAD

**Issue by thomasfw** [humanmade/backupwordpress#997]
Running the latest version, and seeing the following periodically appear in my local environment..

```
Warning: exec(): Unable to fork [echo backupwordpress] in /var/www/public_html/app/plugins/backupwordpress/classes/backup/class-backup-utilities.php on line 55
```

**Comment by willmot** [comment]
Looks like this happening is outside of the control of the plugin, but we should be catching and silencing the error. any chance you could test whether https://github.com/humanmade/backupwordpress/pull/991 fixes this for you?

**Comment by willmot** [comment]
Closing as #991 will fix this.
